# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'homepage.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_homepage(object):
    def setupUi(self, homepage):
        homepage.setObjectName("homepage")
        homepage.resize(952, 638)
        self.centralwidget = QtWidgets.QWidget(homepage)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("background-color: rgb(88, 116, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("images/PoCoH.png"))
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label, 0, QtCore.Qt.AlignHCenter)
        self.gridLayout.addWidget(self.frame, 1, 0, 1, 1)
        homepage.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(homepage)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 952, 22))
        self.menubar.setObjectName("menubar")
        homepage.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(homepage)
        self.statusbar.setObjectName("statusbar")
        homepage.setStatusBar(self.statusbar)

        self.retranslateUi(homepage)
        QtCore.QMetaObject.connectSlotsByName(homepage)

    def retranslateUi(self, homepage):
        _translate = QtCore.QCoreApplication.translate
        homepage.setWindowTitle(_translate("homepage", "MainWindow"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    homepage = QtWidgets.QMainWindow()
    ui = Ui_homepage()
    ui.setupUi(homepage)
    homepage.show()
    sys.exit(app.exec_())
