# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'resgister-section2.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(915, 641)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 260, 221, 91))
        self.label_3.setStyleSheet("background-color: rgb(149, 167, 255);")
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("images/PoCoH.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 921, 601))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("images/login-bg.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(500, 50, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(24)
        font.setBold(True)
        font.setKerning(True)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_9.setObjectName("label_9")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(500, 100, 391, 31))
        font = QtGui.QFont()
        font.setFamily("Poppins SemiBold")
        font.setPointSize(18)
        font.setBold(True)
        font.setKerning(True)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_13.setObjectName("label_13")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(500, 190, 301, 41))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"font: 12pt \"Poppins\";\n"
"border-bottom:2px solid #2a2a2a;\n"
"border-radius: 30px;\n"
"color:#2a2a2a;\n"
"padding-bottom:7px;")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(500, 150, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(510, 470, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("QPushButton#pushButton_3{\n"
"    font: 14pt \"Poppins\";\n"
" color: #ffffff;\n"
" font-size: 18px;\n"
" border-radius: 0.5em;\n"
" border: 1px solid #e8e8e8;\n"
"}\n"
"\n"
"QPushButton#pushButton_3:hover {\n"
" border: 2px solid white;\n"
"color:#090909;\n"
" background: #e8e8e8;\n"
"}\n"
"")
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(500, 360, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(14)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(500, 290, 301, 41))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"font: 12pt \"Poppins\";\n"
"border-bottom:2px solid #2a2a2a;\n"
"border-radius: 30px;\n"
"color:#2a2a2a;\n"
"padding-bottom:7px;")
        self.lineEdit_3.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(690, 470, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton#pushButton_2{\n"
"font: 14pt \"Poppins\";\n"
" color: #090909;\n"
" font-size: 18px;\n"
" border-radius: 0.5em;\n"
" background: #e8e8e8;\n"
" border: 1px solid #e8e8e8;\n"
"}\n"
"\n"
"QPushButton#pushButton_2:hover {\n"
" border: 2px solid white;\n"
"}\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(500, 250, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(14)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(500, 400, 301, 41))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border-bottom:2px solid #2a2a2a;\n"
"font: 12pt \"Poppins\";\n"
"border-radius: 30px;\n"
"color:#2a2a2a;\n"
"padding-bottom:7px;")
        self.lineEdit_4.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label.raise_()
        self.label_3.raise_()
        self.label_9.raise_()
        self.label_13.raise_()
        self.lineEdit_2.raise_()
        self.label_5.raise_()
        self.pushButton_3.raise_()
        self.label_8.raise_()
        self.lineEdit_3.raise_()
        self.pushButton_2.raise_()
        self.label_7.raise_()
        self.lineEdit_4.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 915, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_9.setText(_translate("MainWindow", "REGISTER"))
        self.label_13.setText(_translate("MainWindow", "Section 2: Login Credentials"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "  Create username"))
        self.label_5.setText(_translate("MainWindow", "Username"))
        self.pushButton_3.setText(_translate("MainWindow", "Back"))
        self.label_8.setText(_translate("MainWindow", "Re-Enter Password"))
        self.lineEdit_3.setPlaceholderText(_translate("MainWindow", "  Create password"))
        self.pushButton_2.setText(_translate("MainWindow", "Submit"))
        self.label_7.setText(_translate("MainWindow", "Password"))
        self.lineEdit_4.setPlaceholderText(_translate("MainWindow", "  Re-Enter password"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
