# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'chicken_pox.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_chickenpox(object):
    def setupUi(self, chickenpox):
        chickenpox.setObjectName("chickenpox")
        chickenpox.resize(1104, 804)
        self.centralwidget = QtWidgets.QWidget(chickenpox)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setStyleSheet("background-color: rgb(88, 116, 255);\n"
"/*background-color: rgb(255, 255, 222);*/")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1067, 818))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame.setMaximumSize(QtCore.QSize(16777215, 800))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_8 = QtWidgets.QFrame(self.frame)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_8)
        self.pushButton_2.setStyleSheet("border-radius: 0.5em;\n"
"background-color: rgb(255, 174, 13);\n"
"padding-top: 0.30em;\n"
"padding-bottom: 0.30em;\n"
"padding-left: 0.85em;\n"
"padding-right: 0.85em;\n"
"font: 500 11pt \"Poppins\";")
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_7.addWidget(self.pushButton_2)
        self.verticalLayout.addWidget(self.frame_8, 0, QtCore.Qt.AlignLeft)
        self.frame_6 = QtWidgets.QFrame(self.frame)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_4 = QtWidgets.QLabel(self.frame_6)
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("../images/PoCoH.png"))
        self.label_4.setObjectName("label_4")
        self.verticalLayout_5.addWidget(self.label_4)
        self.verticalLayout.addWidget(self.frame_6, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setMaximumSize(QtCore.QSize(1000, 16777215))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        self.frame_4.setMaximumSize(QtCore.QSize(1000, 1000))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.frame_4)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../images/disease/2.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout_2.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(self.frame_2)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.frame_5)
        self.label_2.setStyleSheet("font: 700 18pt \"Poppins\";")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.horizontalLayout_2.addWidget(self.frame_5)
        self.verticalLayout.addWidget(self.frame_2, 0, QtCore.Qt.AlignHCenter)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_4.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.frame_3)
        self.label_3.setStyleSheet("font: 400 12pt \"Poppins\";")
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3)
        self.verticalLayout.addWidget(self.frame_3, 0, QtCore.Qt.AlignHCenter)
        self.frame_7 = QtWidgets.QFrame(self.frame)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.pushButton = QtWidgets.QPushButton(self.frame_7)
        self.pushButton.setStyleSheet("border-radius: 0.5em;\n"
"background-color: rgb(255, 174, 13);\n"
"padding-top: 0.30em;\n"
"padding-bottom: 0.30em;\n"
"padding-left: 1.5em;\n"
"padding-right: 1.5em;\n"
"font: 500 12pt \"Poppins\";")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_6.addWidget(self.pushButton)
        self.verticalLayout.addWidget(self.frame_7, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout.addWidget(self.frame)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 1, 0, 1, 1)
        chickenpox.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(chickenpox)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1104, 22))
        self.menubar.setObjectName("menubar")
        chickenpox.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(chickenpox)
        self.statusbar.setObjectName("statusbar")
        chickenpox.setStatusBar(self.statusbar)

        self.retranslateUi(chickenpox)
        QtCore.QMetaObject.connectSlotsByName(chickenpox)

    def retranslateUi(self, chickenpox):
        _translate = QtCore.QCoreApplication.translate
        chickenpox.setWindowTitle(_translate("chickenpox", "MainWindow"))
        self.pushButton_2.setText(_translate("chickenpox", "Back"))
        self.label_2.setText(_translate("chickenpox", "Prefered Diets for Chicken pox"))
        self.label_3.setText(_translate("chickenpox", "● Take home-based diet      \n"
"● Light digestible food like khichdi will be easy to digest as well as provide the required calories and proteins\n"
"● Sprouts are good form of protein which helps in increasing immunity\n"
"● Garlic and turmeric in diet boost the immunity as well\n"
"● It\'s important to take diet rich in vitamin A as it helps in healing the skin eg. Green and coloured leafy vegetables\n"
"● Food rich in calcium and magnesium like milk, wheat, beans etc\n"
"● Food rich in zinc help to boost the immunity eg pulses, beans, vegetables        \n"
"● Increased water intake to maintain body hydration\n"
"● Fruits like banana, apple, watermelons. If there are no oral sores and ulcers then citrus fruits like grapes, oranges can also be taken\n"
"● Fruits can also be taken mixed with milkshakes"))
        self.pushButton.setText(_translate("chickenpox", "Okay"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    chickenpox = QtWidgets.QMainWindow()
    ui = Ui_chickenpox()
    ui.setupUi(chickenpox)
    chickenpox.show()
    sys.exit(app.exec_())
