# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'covid_diet.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_covid_diet(object):
    def setupUi(self, covid_diet):
        covid_diet.setObjectName("covid_diet")
        covid_diet.resize(1183, 812)
        self.centralwidget = QtWidgets.QWidget(covid_diet)
        self.centralwidget.setObjectName("centralwidget")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(10, -10, 1082, 731))
        self.scrollArea.setStyleSheet("background-color: rgb(88, 116, 255);\n"
"/*background-color: rgb(255, 255, 222);*/")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 1059, 822))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents_2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.frame.setMaximumSize(QtCore.QSize(16777215, 800))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.frame_16 = QtWidgets.QFrame(self.frame)
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.frame_16)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_16)
        self.pushButton_4.setStyleSheet("border-radius: 0.5em;\n"
"background-color: rgb(255, 174, 13);\n"
"padding-top: 0.30em;\n"
"padding-bottom: 0.30em;\n"
"padding-left: 0.85em;\n"
"padding-right: 0.85em;\n"
"font: 500 11pt \"Poppins\";")
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_15.addWidget(self.pushButton_4)
        self.verticalLayout_14.addWidget(self.frame_16, 0, QtCore.Qt.AlignLeft)
        self.frame_17 = QtWidgets.QFrame(self.frame)
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.frame_17)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.label_7 = QtWidgets.QLabel(self.frame_17)
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("../images/PoCoH.png"))
        self.label_7.setObjectName("label_7")
        self.verticalLayout_16.addWidget(self.label_7)
        self.verticalLayout_14.addWidget(self.frame_17, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.frame_18 = QtWidgets.QFrame(self.frame)
        self.frame_18.setMaximumSize(QtCore.QSize(1000, 16777215))
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_18)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame_19 = QtWidgets.QFrame(self.frame_18)
        self.frame_19.setMaximumSize(QtCore.QSize(2000, 2000))
        self.frame_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.frame_19)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.label_8 = QtWidgets.QLabel(self.frame_19)
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("../images/disease covid.jpg"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_17.addWidget(self.label_8, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout_5.addWidget(self.frame_19)
        self.frame_20 = QtWidgets.QFrame(self.frame_18)
        self.frame_20.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.frame_20)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.label_9 = QtWidgets.QLabel(self.frame_20)
        self.label_9.setStyleSheet("font: 700 18pt \"Poppins\";")
        self.label_9.setObjectName("label_9")
        self.verticalLayout_18.addWidget(self.label_9)
        self.horizontalLayout_5.addWidget(self.frame_20)
        self.verticalLayout_14.addWidget(self.frame_18, 0, QtCore.Qt.AlignHCenter)
        self.frame_21 = QtWidgets.QFrame(self.frame)
        self.frame_21.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_21.setObjectName("frame_21")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.frame_21)
        self.verticalLayout_19.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout_19.setSpacing(0)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.label_10 = QtWidgets.QLabel(self.frame_21)
        self.label_10.setStyleSheet("font: 400 12pt \"Poppins\";")
        self.label_10.setWordWrap(True)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_19.addWidget(self.label_10)
        self.verticalLayout_14.addWidget(self.frame_21, 0, QtCore.Qt.AlignHCenter)
        self.frame_22 = QtWidgets.QFrame(self.frame)
        self.frame_22.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_22.setObjectName("frame_22")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.frame_22)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_22)
        self.pushButton_5.setStyleSheet("border-radius: 0.5em;\n"
"background-color: rgb(255, 174, 13);\n"
"padding-top: 0.30em;\n"
"padding-bottom: 0.30em;\n"
"padding-left: 1.5em;\n"
"padding-right: 1.5em;\n"
"font: 500 12pt \"Poppins\";")
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_20.addWidget(self.pushButton_5)
        self.verticalLayout_14.addWidget(self.frame_22, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_4.addWidget(self.frame)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        covid_diet.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(covid_diet)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1183, 26))
        self.menubar.setObjectName("menubar")
        covid_diet.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(covid_diet)
        self.statusbar.setObjectName("statusbar")
        covid_diet.setStatusBar(self.statusbar)

        self.retranslateUi(covid_diet)
        QtCore.QMetaObject.connectSlotsByName(covid_diet)

    def retranslateUi(self, covid_diet):
        _translate = QtCore.QCoreApplication.translate
        covid_diet.setWindowTitle(_translate("covid_diet", "MainWindow"))
        self.pushButton_4.setText(_translate("covid_diet", "Back"))
        self.label_9.setText(_translate("covid_diet", "Recovery Diets for Covid"))
        self.label_10.setText(_translate("covid_diet", "● Vegetarian \n"
" Try to include a portion of protein-rich food in every meal. Vegetarians can include 2-3 servings/day of pulses, dal, soya, milk & milk products, nuts, and seeds. Also, besan, sattu, khichdi, peanut, paneer, curd, and mushrooms are good options\n"
" ● Non-Vegetarian\n"
" Non-vegetarians can include all of these along with lean meat like eggs, chicken, and fish in their diet.\n"
" Reduce intake of excessive fat and opt for cooking methods that require less or no fat, such as steaming, grilling, or sautéing instead of frying foods. Choose foods that contain healthy sources of unsaturated fats, like fish and nuts.\n"
" Vitamins, minerals, and antioxidants present in colorful fruits, and vegetables facilitate a speedy recovery. Try to include at least 5-6 servings of fruits and vegetables daily meal plan. You can add fruits to your milkshakes or smoothies and consume seasonal vegetables in forms such as cooked, sautéed, steamed, or boiled.  "))
        self.pushButton_5.setText(_translate("covid_diet", "Okay"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    covid_diet = QtWidgets.QMainWindow()
    ui = Ui_covid_diet()
    ui.setupUi(covid_diet)
    covid_diet.show()
    sys.exit(app.exec_())
