# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'l_homepage.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_l_homepage(object):
    def setupUi(self, l_homepage):
        l_homepage.setObjectName("l_homepage")
        l_homepage.resize(919, 638)
        self.centralwidget = QtWidgets.QWidget(l_homepage)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("background-color: rgb(88, 116, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_3)
        self.stackedWidget.setEnabled(True)
        self.stackedWidget.setObjectName("stackedWidget")
        self.home = QtWidgets.QWidget()
        self.home.setObjectName("home")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.home)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_7 = QtWidgets.QFrame(self.home)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_8 = QtWidgets.QFrame(self.frame_7)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.frame_10 = QtWidgets.QFrame(self.frame_8)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_6.addWidget(self.frame_10)
        self.frame_11 = QtWidgets.QFrame(self.frame_8)
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_11)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label = QtWidgets.QLabel(self.frame_11)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("images/PoCoH.png"))
        self.label.setScaledContents(False)
        self.label.setObjectName("label")
        self.horizontalLayout_7.addWidget(self.label)
        self.horizontalLayout_6.addWidget(self.frame_11, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.frame_12 = QtWidgets.QFrame(self.frame_8)
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.horizontalLayout_6.addWidget(self.frame_12)
        self.verticalLayout.addWidget(self.frame_8)
        self.frame_9 = QtWidgets.QFrame(self.frame_7)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.frame_9)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(18)
        font.setItalic(True)
        self.label_2.setFont(font)
        self.label_2.setAutoFillBackground(False)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.verticalLayout.addWidget(self.frame_9)
        self.gridLayout_2.addWidget(self.frame_7, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.home)
        self.precautions = QtWidgets.QWidget()
        self.precautions.setObjectName("precautions")
        self.label_13 = QtWidgets.QLabel(self.precautions)
        self.label_13.setGeometry(QtCore.QRect(330, 150, 191, 141))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(16)
        font.setBold(True)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.learnmore = QtWidgets.QPushButton(self.precautions)
        self.learnmore.setGeometry(QtCore.QRect(400, 330, 75, 24))
        self.learnmore.setStyleSheet("/* From cssbuttons.io */\n"
"QPushButton#learnmore{\n"
" position: relative;\n"
" display: inline-block;\n"
" cursor: pointer;\n"
" outline: none;\n"
" border: 0;\n"
" vertical-align: middle;\n"
" text-decoration: none;\n"
" background: transparent;\n"
" padding: 0;\n"
" font-size: inherit;\n"
" font-family: inherit;\n"
"}\n"
"\n"
"QPushButton#learnmore.learn-more {\n"
" width: 12rem;\n"
" height: auto;\n"
"}\n"
"\n"
"QPushButton#learnmore.learn-more .circle {\n"
" transition: all 0.45s cubic-bezier(0.65, 0, 0.076, 1);\n"
" position: relative;\n"
" display: block;\n"
" margin: 0;\n"
" width: 3rem;\n"
" height: 3rem;\n"
" background: #282936;\n"
" border-radius: 1.625rem;\n"
"}\n"
"\n"
"QPushButton#learnmore.learn-more .circle .icon {\n"
" transition: all 0.45s cubic-bezier(0.65, 0, 0.076, 1);\n"
" position: absolute;\n"
" top: 0;\n"
" bottom: 0;\n"
" margin: auto;\n"
" background: #fff;\n"
"}\n"
"\n"
"QPushButton#learnmore.learn-more .circle .icon.arrow {\n"
" transition: all 0.45s cubic-bezier(0.65, 0, 0.076, 1);\n"
" left: 0.625rem;\n"
" width: 1.125rem;\n"
" height: 0.125rem;\n"
" background: none;\n"
"}\n"
"\n"
"QPushButton#learnmore.learn-more .circle .icon.arrow::before {\n"
" position: absolute;\n"
" content: \"\";\n"
" top: -0.29rem;\n"
" right: 0.0625rem;\n"
" width: 0.625rem;\n"
" height: 0.625rem;\n"
" border-top: 0.125rem solid #fff;\n"
" border-right: 0.125rem solid #fff;\n"
" transform: rotate(45deg);\n"
"}\n"
"\n"
"QPushButton#learnmore.learn-more .button-text {\n"
" transition: all 0.45s cubic-bezier(0.65, 0, 0.076, 1);\n"
" position: absolute;\n"
" top: 0;\n"
" left: 0;\n"
" right: 0;\n"
" bottom: 0;\n"
" padding: 0.75rem 0;\n"
" margin: 0 0 0 1.85rem;\n"
" color: #282936;\n"
" font-weight: 700;\n"
" line-height: 1.6;\n"
" text-align: center;\n"
" text-transform: uppercase;\n"
"}\n"
"\n"
"QPushButton#learnmore:hover .circle {\n"
" width: 100%;\n"
"}\n"
"\n"
"QPushButton#learnmore:hover .circle .icon.arrow {\n"
" background: #fff;\n"
" transform: translate(1rem, 0);\n"
"}\n"
"\n"
"QPushButton#learnmore:hover .button-text {\n"
" color: #fff;\n"
"}")
        self.learnmore.setObjectName("learnmore")
        self.stackedWidget.addWidget(self.precautions)
        self.profile = QtWidgets.QWidget()
        self.profile.setObjectName("profile")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.profile)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame_5 = QtWidgets.QFrame(self.profile)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_13 = QtWidgets.QFrame(self.frame_5)
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.label_3 = QtWidgets.QLabel(self.frame_13)
        self.label_3.setGeometry(QtCore.QRect(20, 20, 121, 121))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("images/icons/profile.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame_13)
        self.label_4.setGeometry(QtCore.QRect(20, 160, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Poppins SemiBold")
        font.setPointSize(14)
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.frame_13)
        self.frame_14 = QtWidgets.QFrame(self.frame_5)
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_14)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.blogout = QtWidgets.QPushButton(self.frame_14)
        self.blogout.setStyleSheet("QPushButton#blogout{\n"
"font: 500 12pt \"Poppins\";\n"
"padding-left: 0.5em;\n"
"padding-right: 0.5em;\n"
"padding-top: 0.1em;\n"
"padding-bottom: 0.1em;\n"
" color: #090909;\n"
" border-radius: 0.5em;\n"
" background: #e8e8e8;\n"
" border: 1px solid #e8e8e8;\n"
"}\n"
"\n"
"\n"
"QPushButton#blogout:hover {\n"
"border: 1px solid white;\n"
"}")
        self.blogout.setObjectName("blogout")
        self.verticalLayout_6.addWidget(self.blogout, 0, QtCore.Qt.AlignLeft)
        self.verticalLayout_4.addWidget(self.frame_14, 0, QtCore.Qt.AlignBottom)
        self.gridLayout_3.addWidget(self.frame_5, 0, 0, 1, 1)
        self.frame_6 = QtWidgets.QFrame(self.profile)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.frame_6)
        self.label_5.setStyleSheet("font: 600 12pt \"Poppins\";")
        self.label_5.setObjectName("label_5")
        self.verticalLayout_5.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.frame_6)
        self.label_6.setStyleSheet("font: 12pt \"Poppins\";")
        self.label_6.setObjectName("label_6")
        self.verticalLayout_5.addWidget(self.label_6)
        self.label_8 = QtWidgets.QLabel(self.frame_6)
        self.label_8.setStyleSheet("font: 600 12pt \"Poppins\";")
        self.label_8.setObjectName("label_8")
        self.verticalLayout_5.addWidget(self.label_8)
        self.label_7 = QtWidgets.QLabel(self.frame_6)
        self.label_7.setStyleSheet("font: 12pt \"Poppins\";")
        self.label_7.setObjectName("label_7")
        self.verticalLayout_5.addWidget(self.label_7)
        self.label_10 = QtWidgets.QLabel(self.frame_6)
        self.label_10.setStyleSheet("font: 600 12pt \"Poppins\";")
        self.label_10.setObjectName("label_10")
        self.verticalLayout_5.addWidget(self.label_10)
        self.label_9 = QtWidgets.QLabel(self.frame_6)
        self.label_9.setStyleSheet("font: 12pt \"Poppins\";")
        self.label_9.setObjectName("label_9")
        self.verticalLayout_5.addWidget(self.label_9)
        self.label_12 = QtWidgets.QLabel(self.frame_6)
        self.label_12.setStyleSheet("font: 600 12pt \"Poppins\";")
        self.label_12.setObjectName("label_12")
        self.verticalLayout_5.addWidget(self.label_12)
        self.label_11 = QtWidgets.QLabel(self.frame_6)
        self.label_11.setStyleSheet("font: 12pt \"Poppins\";")
        self.label_11.setObjectName("label_11")
        self.verticalLayout_5.addWidget(self.label_11)
        self.gridLayout_3.addWidget(self.frame_6, 0, 1, 1, 1)
        self.stackedWidget.addWidget(self.profile)
        self.exercises = QtWidgets.QWidget()
        self.exercises.setObjectName("exercises")
        self.label_15 = QtWidgets.QLabel(self.exercises)
        self.label_15.setGeometry(QtCore.QRect(300, 180, 241, 101))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(16)
        font.setBold(True)
        self.label_15.setFont(font)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.stackedWidget.addWidget(self.exercises)
        self.diet = QtWidgets.QWidget()
        self.diet.setObjectName("diet")
        self.label_16 = QtWidgets.QLabel(self.diet)
        self.label_16.setGeometry(QtCore.QRect(300, 170, 251, 131))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(16)
        font.setBold(True)
        self.label_16.setFont(font)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.stackedWidget.addWidget(self.diet)
        self.homeremedies = QtWidgets.QWidget()
        self.homeremedies.setObjectName("homeremedies")
        self.label_14 = QtWidgets.QLabel(self.homeremedies)
        self.label_14.setGeometry(QtCore.QRect(290, 170, 271, 131))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(16)
        font.setBold(True)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.stackedWidget.addWidget(self.homeremedies)
        self.horizontalLayout_2.addWidget(self.stackedWidget)
        self.verticalLayout_2.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setStyleSheet("background-color: #f6f6f6;\n"
"border-radius: 1.5em;")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.bhome = QtWidgets.QPushButton(self.frame_4)
        self.bhome.setMinimumSize(QtCore.QSize(0, 50))
        self.bhome.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/icons/c-home.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bhome.setIcon(icon)
        self.bhome.setIconSize(QtCore.QSize(35, 35))
        self.bhome.setObjectName("bhome")
        self.horizontalLayout_5.addWidget(self.bhome)
        self.bprecautions = QtWidgets.QPushButton(self.frame_4)
        self.bprecautions.setMinimumSize(QtCore.QSize(0, 50))
        self.bprecautions.setStyleSheet("")
        self.bprecautions.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("images/icons/c-precautions.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bprecautions.setIcon(icon1)
        self.bprecautions.setIconSize(QtCore.QSize(35, 35))
        self.bprecautions.setObjectName("bprecautions")
        self.horizontalLayout_5.addWidget(self.bprecautions)
        self.bexercise = QtWidgets.QPushButton(self.frame_4)
        self.bexercise.setMinimumSize(QtCore.QSize(0, 50))
        self.bexercise.setStyleSheet("border: none;")
        self.bexercise.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("images/icons/c-exercise.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bexercise.setIcon(icon2)
        self.bexercise.setIconSize(QtCore.QSize(35, 35))
        self.bexercise.setObjectName("bexercise")
        self.horizontalLayout_5.addWidget(self.bexercise)
        self.bdiet = QtWidgets.QPushButton(self.frame_4)
        self.bdiet.setMinimumSize(QtCore.QSize(0, 50))
        self.bdiet.setStyleSheet("border: none;")
        self.bdiet.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("images/icons/c-diet.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bdiet.setIcon(icon3)
        self.bdiet.setIconSize(QtCore.QSize(35, 35))
        self.bdiet.setObjectName("bdiet")
        self.horizontalLayout_5.addWidget(self.bdiet)
        self.bremedies = QtWidgets.QPushButton(self.frame_4)
        self.bremedies.setMinimumSize(QtCore.QSize(0, 50))
        self.bremedies.setStyleSheet("border: none;")
        self.bremedies.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("images/icons/c-home-remedies.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bremedies.setIcon(icon4)
        self.bremedies.setIconSize(QtCore.QSize(35, 35))
        self.bremedies.setObjectName("bremedies")
        self.horizontalLayout_5.addWidget(self.bremedies)
        self.bprofile = QtWidgets.QPushButton(self.frame_4)
        self.bprofile.setMinimumSize(QtCore.QSize(0, 50))
        self.bprofile.setStyleSheet("border: none;")
        self.bprofile.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("images/icons/profile-black.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bprofile.setIcon(icon5)
        self.bprofile.setIconSize(QtCore.QSize(35, 35))
        self.bprofile.setObjectName("bprofile")
        self.horizontalLayout_5.addWidget(self.bprofile)
        self.verticalLayout_2.addWidget(self.frame_4)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        l_homepage.setCentralWidget(self.centralwidget)

        self.retranslateUi(l_homepage)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(l_homepage)

    def retranslateUi(self, l_homepage):
        _translate = QtCore.QCoreApplication.translate
        l_homepage.setWindowTitle(_translate("l_homepage", "MainWindow"))
        self.label_2.setText(_translate("l_homepage", "An apple a day keeps the doctor away!"))
        self.label_13.setText(_translate("l_homepage", "PRECAUTIONS"))
        self.learnmore.setText(_translate("l_homepage", "PushButton"))
        self.label_4.setText(_translate("l_homepage", "John Doe"))
        self.blogout.setText(_translate("l_homepage", "Log Out"))
        self.label_5.setText(_translate("l_homepage", "Username:"))
        self.label_6.setText(_translate("l_homepage", "<Username of person>"))
        self.label_8.setText(_translate("l_homepage", "Date of Birth:"))
        self.label_7.setText(_translate("l_homepage", "<Date of birth of person>"))
        self.label_10.setText(_translate("l_homepage", "Username:"))
        self.label_9.setText(_translate("l_homepage", "<Username of person>"))
        self.label_12.setText(_translate("l_homepage", "Username:"))
        self.label_11.setText(_translate("l_homepage", "<Username of person>"))
        self.label_15.setText(_translate("l_homepage", "EXERCISES"))
        self.label_16.setText(_translate("l_homepage", "DIET"))
        self.label_14.setText(_translate("l_homepage", "REMEDIES"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    l_homepage = QtWidgets.QMainWindow()
    ui = Ui_l_homepage()
    ui.setupUi(l_homepage)
    l_homepage.show()
    sys.exit(app.exec_())
