# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'l_homepage.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_l_homepage(object):
    def setupUi(self, l_homepage):
        l_homepage.setObjectName("l_homepage")
        l_homepage.resize(1115, 849)
        self.centralwidget = QtWidgets.QWidget(l_homepage)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("background-color: rgb(88, 116, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_2)
        self.stackedWidget.setEnabled(True)
        self.stackedWidget.setObjectName("stackedWidget")
        self.home = QtWidgets.QWidget()
        self.home.setObjectName("home")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.home)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_7 = QtWidgets.QFrame(self.home)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_8 = QtWidgets.QFrame(self.frame_7)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.frame_10 = QtWidgets.QFrame(self.frame_8)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_29 = QtWidgets.QVBoxLayout(self.frame_10)
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        self.blogout_2 = QtWidgets.QPushButton(self.frame_10)
        self.blogout_2.setStyleSheet("QPushButton#blogout_2{\n"
"font: 500 12pt \"Poppins\";\n"
"padding-left: 0.5em;\n"
"padding-right: 0.5em;\n"
"padding-top: 0.1em;\n"
"padding-bottom: 0.1em;\n"
" color: #090909;\n"
" border-radius: 0.5em;\n"
" background: #e8e8e8;\n"
" border: 1px solid #e8e8e8;\n"
"}\n"
"\n"
"\n"
"QPushButton#blogout_2:hover {\n"
"border: 1px solid white;\n"
"}")
        self.blogout_2.setObjectName("blogout_2")
        self.verticalLayout_29.addWidget(self.blogout_2)
        self.horizontalLayout_6.addWidget(self.frame_10, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.frame_11 = QtWidgets.QFrame(self.frame_8)
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_11)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label = QtWidgets.QLabel(self.frame_11)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../images/PoCoH.png"))
        self.label.setScaledContents(False)
        self.label.setObjectName("label")
        self.horizontalLayout_7.addWidget(self.label)
        self.horizontalLayout_6.addWidget(self.frame_11, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.frame_12 = QtWidgets.QFrame(self.frame_8)
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.horizontalLayout_6.addWidget(self.frame_12)
        self.verticalLayout.addWidget(self.frame_8)
        self.frame_15 = QtWidgets.QFrame(self.frame_7)
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_15)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_17 = QtWidgets.QLabel(self.frame_15)
        self.label_17.setStyleSheet("font: 600 19pt \"Poppins\";")
        self.label_17.setObjectName("label_17")
        self.verticalLayout_7.addWidget(self.label_17)
        self.verticalLayout.addWidget(self.frame_15)
        self.frame_9 = QtWidgets.QFrame(self.frame_7)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.frame_9)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(18)
        font.setItalic(True)
        self.label_2.setFont(font)
        self.label_2.setAutoFillBackground(False)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.verticalLayout.addWidget(self.frame_9)
        self.gridLayout_2.addWidget(self.frame_7, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.home)
        self.precautions = QtWidgets.QWidget()
        self.precautions.setObjectName("precautions")
        self.label_13 = QtWidgets.QLabel(self.precautions)
        self.label_13.setGeometry(QtCore.QRect(330, 150, 191, 141))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(16)
        font.setBold(True)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.stackedWidget.addWidget(self.precautions)
        self.profile = QtWidgets.QWidget()
        self.profile.setObjectName("profile")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.profile)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame_5 = QtWidgets.QFrame(self.profile)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_13 = QtWidgets.QFrame(self.frame_5)
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.label_3 = QtWidgets.QLabel(self.frame_13)
        self.label_3.setGeometry(QtCore.QRect(20, 20, 121, 121))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("../images/icons/profile.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.name = QtWidgets.QLabel(self.frame_13)
        self.name.setGeometry(QtCore.QRect(20, 160, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Poppins SemiBold")
        font.setPointSize(14)
        font.setBold(True)
        self.name.setFont(font)
        self.name.setObjectName("name")
        self.verticalLayout_4.addWidget(self.frame_13)
        self.frame_56 = QtWidgets.QFrame(self.frame_5)
        self.frame_56.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_56.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_56.setObjectName("frame_56")
        self.verticalLayout_46 = QtWidgets.QVBoxLayout(self.frame_56)
        self.verticalLayout_46.setObjectName("verticalLayout_46")
        self.beditprof = QtWidgets.QPushButton(self.frame_56)
        self.beditprof.setStyleSheet("border-radius: 0.5em;\n"
"background-color: rgb(255, 174, 13);\n"
"padding-top: 0.30em;\n"
"padding-bottom: 0.30em;\n"
"padding-left: 0.5em;\n"
"padding-right: 0.5em;\n"
"font: 500 10pt \"Poppins\";")
        self.beditprof.setObjectName("beditprof")
        self.verticalLayout_46.addWidget(self.beditprof)
        self.verticalLayout_4.addWidget(self.frame_56, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.frame_14 = QtWidgets.QFrame(self.frame_5)
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_14)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.blogout = QtWidgets.QPushButton(self.frame_14)
        self.blogout.setStyleSheet("QPushButton#blogout{\n"
"font: 500 12pt \"Poppins\";\n"
"padding-left: 0.5em;\n"
"padding-right: 0.5em;\n"
"padding-top: 0.1em;\n"
"padding-bottom: 0.1em;\n"
" color: #090909;\n"
" border-radius: 0.5em;\n"
" background: #e8e8e8;\n"
" border: 1px solid #e8e8e8;\n"
"}\n"
"\n"
"\n"
"QPushButton#blogout:hover {\n"
"border: 1px solid white;\n"
"}")
        self.blogout.setObjectName("blogout")
        self.verticalLayout_6.addWidget(self.blogout, 0, QtCore.Qt.AlignLeft)
        self.verticalLayout_4.addWidget(self.frame_14, 0, QtCore.Qt.AlignBottom)
        self.gridLayout_3.addWidget(self.frame_5, 0, 0, 1, 1)
        self.frame_6 = QtWidgets.QFrame(self.profile)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.frame_6)
        self.label_5.setStyleSheet("font: 600 12pt \"Poppins\";\n"
"padding-bottom: 0.4em;")
        self.label_5.setObjectName("label_5")
        self.verticalLayout_5.addWidget(self.label_5, 0, QtCore.Qt.AlignBottom)
        self.username = QtWidgets.QLabel(self.frame_6)
        self.username.setStyleSheet("font: 12pt \"Poppins\";")
        self.username.setObjectName("username")
        self.verticalLayout_5.addWidget(self.username, 0, QtCore.Qt.AlignTop)
        self.label_8 = QtWidgets.QLabel(self.frame_6)
        self.label_8.setStyleSheet("font: 600 12pt \"Poppins\";\n"
"padding-bottom: 0.4em;")
        self.label_8.setObjectName("label_8")
        self.verticalLayout_5.addWidget(self.label_8, 0, QtCore.Qt.AlignBottom)
        self.email = QtWidgets.QLabel(self.frame_6)
        self.email.setStyleSheet("font: 12pt \"Poppins\";")
        self.email.setObjectName("email")
        self.verticalLayout_5.addWidget(self.email, 0, QtCore.Qt.AlignTop)
        self.label_10 = QtWidgets.QLabel(self.frame_6)
        self.label_10.setStyleSheet("font: 600 12pt \"Poppins\";\n"
"padding-bottom: 0.4em;")
        self.label_10.setObjectName("label_10")
        self.verticalLayout_5.addWidget(self.label_10, 0, QtCore.Qt.AlignBottom)
        self.mobile = QtWidgets.QLabel(self.frame_6)
        self.mobile.setStyleSheet("font: 12pt \"Poppins\";")
        self.mobile.setObjectName("mobile")
        self.verticalLayout_5.addWidget(self.mobile, 0, QtCore.Qt.AlignTop)
        self.label_12 = QtWidgets.QLabel(self.frame_6)
        self.label_12.setStyleSheet("font: 600 12pt \"Poppins\";\n"
"padding-bottom: 0.4em;")
        self.label_12.setObjectName("label_12")
        self.verticalLayout_5.addWidget(self.label_12, 0, QtCore.Qt.AlignBottom)
        self.dob = QtWidgets.QLabel(self.frame_6)
        self.dob.setStyleSheet("font: 12pt \"Poppins\";")
        self.dob.setObjectName("dob")
        self.verticalLayout_5.addWidget(self.dob, 0, QtCore.Qt.AlignTop)
        self.gridLayout_3.addWidget(self.frame_6, 0, 1, 1, 1)
        self.stackedWidget.addWidget(self.profile)
        self.exercises = QtWidgets.QWidget()
        self.exercises.setObjectName("exercises")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.exercises)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.scrollArea = QtWidgets.QScrollArea(self.exercises)
        self.scrollArea.setStyleSheet("/*  HANDLE BAR VERTICAL */\n"
"QScrollBar::handle:vertical {    \n"
"    background-color: rgb(80, 80, 122);\n"
"    min-height: 30px;\n"
"    border-radius: 7px;\n"
"}\n"
"QScrollBar::handle:vertical:hover{    \n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QScrollBar::handle:vertical:pressed {    \n"
"    background-color: rgb(67, 67, 67);\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background-color: rgb(59, 59, 90);\n"
"    height: 15px;\n"
"    border-top-left-radius: 7px;\n"
"    border-top-right-radius: 7px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:vertical:hover {    \n"
"    \n"
"    background-color: rgb(25, 25, 255);\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {    \n"
"    background-color: rgb(185, 0, 92);\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line:vertical {\n"
"    border: none;\n"
"    background-color: rgb(59, 59, 90);\n"
"    height: 15px;\n"
"    border-bottom-left-radius: 7px;\n"
"    border-bottom-right-radius: 7px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:vertical:hover {    \n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {    \n"
"    background-color: rgb(185, 0, 92);\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1020, 1476))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.frame_36 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_36.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_36.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_36.setObjectName("frame_36")
        self.verticalLayout_28 = QtWidgets.QVBoxLayout(self.frame_36)
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.label_36 = QtWidgets.QLabel(self.frame_36)
        self.label_36.setText("")
        self.label_36.setPixmap(QtGui.QPixmap("../images/PoCoH.png"))
        self.label_36.setScaledContents(True)
        self.label_36.setObjectName("label_36")
        self.verticalLayout_28.addWidget(self.label_36)
        self.verticalLayout_9.addWidget(self.frame_36, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.frame_35 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_35.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_35.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_35.setObjectName("frame_35")
        self.verticalLayout_27 = QtWidgets.QVBoxLayout(self.frame_35)
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.label_37 = QtWidgets.QLabel(self.frame_35)
        self.label_37.setStyleSheet("font: 600 18pt \"Poppins\";")
        self.label_37.setObjectName("label_37")
        self.verticalLayout_27.addWidget(self.label_37)
        self.verticalLayout_9.addWidget(self.frame_35)
        self.frame_16 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_16.setMinimumSize(QtCore.QSize(0, 1200))
        self.frame_16.setStyleSheet("")
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_16)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.frame_19 = QtWidgets.QFrame(self.frame_16)
        self.frame_19.setMaximumSize(QtCore.QSize(280, 400))
        self.frame_19.setStyleSheet("background-color: rgb(255, 255, 235);\n"
"border-radius: 0.5em;")
        self.frame_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.frame_19)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.frame_31 = QtWidgets.QFrame(self.frame_19)
        self.frame_31.setMaximumSize(QtCore.QSize(700, 360))
        self.frame_31.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_31.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_31.setObjectName("frame_31")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.frame_31)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.label_30 = QtWidgets.QLabel(self.frame_31)
        self.label_30.setMaximumSize(QtCore.QSize(1000, 7000))
        self.label_30.setText("")
        self.label_30.setPixmap(QtGui.QPixmap("../images/exercise/pocoh5.jpg"))
        self.label_30.setScaledContents(True)
        self.label_30.setObjectName("label_30")
        self.verticalLayout_22.addWidget(self.label_30)
        self.verticalLayout_21.addWidget(self.frame_31)
        self.frame_32 = QtWidgets.QFrame(self.frame_19)
        self.frame_32.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_32.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_32.setObjectName("frame_32")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.frame_32)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.label_32 = QtWidgets.QLabel(self.frame_32)
        self.label_32.setStyleSheet("font: 600 12pt \"Poppins\";")
        self.label_32.setWordWrap(True)
        self.label_32.setObjectName("label_32")
        self.verticalLayout_23.addWidget(self.label_32)
        self.label_31 = QtWidgets.QLabel(self.frame_32)
        self.label_31.setStyleSheet("font: 10pt \"Poppins\";")
        self.label_31.setWordWrap(True)
        self.label_31.setObjectName("label_31")
        self.verticalLayout_23.addWidget(self.label_31)
        self.url5 = QtWidgets.QPushButton(self.frame_32)
        self.url5.setStyleSheet("border-radius: 0.5em;\n"
"background-color: rgb(255, 174, 13);\n"
"padding-top: 0.30em;\n"
"padding-bottom: 0.30em;\n"
"font: 500 10pt \"Poppins\";")
        self.url5.setObjectName("url5")
        self.verticalLayout_23.addWidget(self.url5)
        self.verticalLayout_21.addWidget(self.frame_32)
        self.gridLayout_4.addWidget(self.frame_19, 2, 0, 1, 1)
        self.frame_18 = QtWidgets.QFrame(self.frame_16)
        self.frame_18.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_18.setMaximumSize(QtCore.QSize(280, 400))
        self.frame_18.setStyleSheet("background-color: rgb(255, 255, 235);\n"
"border-radius: 0.5em;")
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout(self.frame_18)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.frame_33 = QtWidgets.QFrame(self.frame_18)
        self.frame_33.setMaximumSize(QtCore.QSize(700, 360))
        self.frame_33.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_33.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_33.setObjectName("frame_33")
        self.verticalLayout_26 = QtWidgets.QVBoxLayout(self.frame_33)
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.label_33 = QtWidgets.QLabel(self.frame_33)
        self.label_33.setMaximumSize(QtCore.QSize(1000, 7000))
        self.label_33.setText("")
        self.label_33.setPixmap(QtGui.QPixmap("../images/exercise/pocoh6.jpg"))
        self.label_33.setScaledContents(True)
        self.label_33.setObjectName("label_33")
        self.verticalLayout_26.addWidget(self.label_33)
        self.verticalLayout_24.addWidget(self.frame_33)
        self.frame_34 = QtWidgets.QFrame(self.frame_18)
        self.frame_34.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_34.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_34.setObjectName("frame_34")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout(self.frame_34)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.label_34 = QtWidgets.QLabel(self.frame_34)
        self.label_34.setStyleSheet("font: 600 12pt \"Poppins\";")
        self.label_34.setWordWrap(True)
        self.label_34.setObjectName("label_34")
        self.verticalLayout_25.addWidget(self.label_34)
        self.label_35 = QtWidgets.QLabel(self.frame_34)
        self.label_35.setStyleSheet("font: 10pt \"Poppins\";")
        self.label_35.setWordWrap(True)
        self.label_35.setObjectName("label_35")
        self.verticalLayout_25.addWidget(self.label_35)
        self.url6 = QtWidgets.QPushButton(self.frame_34)
        self.url6.setStyleSheet("border-radius: 0.5em;\n"
"background-color: rgb(255, 174, 13);\n"
"padding-top: 0.30em;\n"
"padding-bottom: 0.30em;\n"
"font: 500 10pt \"Poppins\";")
        self.url6.setObjectName("url6")
        self.verticalLayout_25.addWidget(self.url6)
        self.verticalLayout_24.addWidget(self.frame_34)
        self.gridLayout_4.addWidget(self.frame_18, 2, 1, 1, 1)
        self.frame_17 = QtWidgets.QFrame(self.frame_16)
        self.frame_17.setMaximumSize(QtCore.QSize(280, 400))
        self.frame_17.setStyleSheet("background-color: rgb(255, 255, 235);\n"
"border-radius: 0.5em;")
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_17)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.frame_23 = QtWidgets.QFrame(self.frame_17)
        self.frame_23.setMaximumSize(QtCore.QSize(700, 360))
        self.frame_23.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_23.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_23.setObjectName("frame_23")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_23)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_15 = QtWidgets.QLabel(self.frame_23)
        self.label_15.setMaximumSize(QtCore.QSize(1000, 7000))
        self.label_15.setText("")
        self.label_15.setPixmap(QtGui.QPixmap("../images/exercise/pocoh1.jpg"))
        self.label_15.setScaledContents(True)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_10.addWidget(self.label_15)
        self.gridLayout_5.addWidget(self.frame_23, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.frame_24 = QtWidgets.QFrame(self.frame_17)
        self.frame_24.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_24.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_24.setObjectName("frame_24")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_24)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_19 = QtWidgets.QLabel(self.frame_24)
        self.label_19.setStyleSheet("font: 600 12pt \"Poppins\";")
        self.label_19.setScaledContents(True)
        self.label_19.setWordWrap(True)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_11.addWidget(self.label_19)
        self.label_20 = QtWidgets.QLabel(self.frame_24)
        self.label_20.setStyleSheet("font: 10pt \"Poppins\";")
        self.label_20.setWordWrap(True)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_11.addWidget(self.label_20)
        self.url1 = QtWidgets.QPushButton(self.frame_24)
        self.url1.setStyleSheet("border-radius: 0.5em;\n"
"background-color: rgb(255, 174, 13);\n"
"\n"
"padding-top: 0.30em;\n"
"padding-bottom: 0.30em;\n"
"font: 500 10pt \"Poppins\";")
        self.url1.setObjectName("url1")
        self.verticalLayout_11.addWidget(self.url1)
        self.gridLayout_5.addWidget(self.frame_24, 1, 0, 1, 1)
        self.gridLayout_4.addWidget(self.frame_17, 0, 0, 1, 1)
        self.frame_20 = QtWidgets.QFrame(self.frame_16)
        self.frame_20.setMaximumSize(QtCore.QSize(280, 400))
        self.frame_20.setStyleSheet("background-color: rgb(255, 255, 235);\n"
"border-radius: 0.5em;")
        self.frame_20.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frame_20)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.frame_25 = QtWidgets.QFrame(self.frame_20)
        self.frame_25.setMaximumSize(QtCore.QSize(700, 360))
        self.frame_25.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_25.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_25.setObjectName("frame_25")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frame_25)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_21 = QtWidgets.QLabel(self.frame_25)
        self.label_21.setMaximumSize(QtCore.QSize(1000, 7000))
        self.label_21.setText("")
        self.label_21.setPixmap(QtGui.QPixmap("../images/exercise/pocoh2.jpg"))
        self.label_21.setScaledContents(True)
        self.label_21.setOpenExternalLinks(True)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_13.addWidget(self.label_21)
        self.verticalLayout_12.addWidget(self.frame_25, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.frame_26 = QtWidgets.QFrame(self.frame_20)
        self.frame_26.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_26.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_26.setObjectName("frame_26")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.frame_26)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_22 = QtWidgets.QLabel(self.frame_26)
        self.label_22.setStyleSheet("font: 600 12pt \"Poppins\";")
        self.label_22.setWordWrap(True)
        self.label_22.setObjectName("label_22")
        self.verticalLayout_14.addWidget(self.label_22)
        self.label_23 = QtWidgets.QLabel(self.frame_26)
        self.label_23.setStyleSheet("font: 10pt \"Poppins\";")
        self.label_23.setWordWrap(True)
        self.label_23.setObjectName("label_23")
        self.verticalLayout_14.addWidget(self.label_23)
        self.url2 = QtWidgets.QPushButton(self.frame_26)
        self.url2.setStyleSheet("border-radius: 0.5em;\n"
"background-color: rgb(255, 174, 13);\n"
"padding-top: 0.30em;\n"
"padding-bottom: 0.30em;\n"
"font: 500 10pt \"Poppins\";")
        self.url2.setObjectName("url2")
        self.verticalLayout_14.addWidget(self.url2)
        self.verticalLayout_12.addWidget(self.frame_26)
        self.gridLayout_4.addWidget(self.frame_20, 0, 1, 1, 1)
        self.frame_21 = QtWidgets.QFrame(self.frame_16)
        self.frame_21.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_21.setMaximumSize(QtCore.QSize(280, 400))
        self.frame_21.setStyleSheet("background-color: rgb(255, 255, 235);\n"
"border-radius: 0.5em;")
        self.frame_21.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_21.setObjectName("frame_21")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.frame_21)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.frame_27 = QtWidgets.QFrame(self.frame_21)
        self.frame_27.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_27.setMaximumSize(QtCore.QSize(700, 360))
        self.frame_27.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_27.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_27.setObjectName("frame_27")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.frame_27)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.label_24 = QtWidgets.QLabel(self.frame_27)
        self.label_24.setMaximumSize(QtCore.QSize(1000, 7000))
        self.label_24.setText("")
        self.label_24.setPixmap(QtGui.QPixmap("../images/exercise/pocoh3.jpg"))
        self.label_24.setScaledContents(True)
        self.label_24.setObjectName("label_24")
        self.verticalLayout_16.addWidget(self.label_24)
        self.verticalLayout_15.addWidget(self.frame_27)
        self.frame_28 = QtWidgets.QFrame(self.frame_21)
        self.frame_28.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_28.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_28.setObjectName("frame_28")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.frame_28)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.label_25 = QtWidgets.QLabel(self.frame_28)
        self.label_25.setStyleSheet("font: 600 12pt \"Poppins\";")
        self.label_25.setWordWrap(True)
        self.label_25.setObjectName("label_25")
        self.verticalLayout_17.addWidget(self.label_25)
        self.label_26 = QtWidgets.QLabel(self.frame_28)
        self.label_26.setStyleSheet("font: 10pt \"Poppins\";")
        self.label_26.setWordWrap(True)
        self.label_26.setObjectName("label_26")
        self.verticalLayout_17.addWidget(self.label_26)
        self.url3 = QtWidgets.QPushButton(self.frame_28)
        self.url3.setStyleSheet("border-radius: 0.5em;\n"
"background-color: rgb(255, 174, 13);\n"
"padding-top: 0.30em;\n"
"padding-bottom: 0.30em;\n"
"font: 500 10pt \"Poppins\";")
        self.url3.setObjectName("url3")
        self.verticalLayout_17.addWidget(self.url3)
        self.verticalLayout_15.addWidget(self.frame_28)
        self.gridLayout_4.addWidget(self.frame_21, 1, 0, 1, 1)
        self.frame_22 = QtWidgets.QFrame(self.frame_16)
        self.frame_22.setMaximumSize(QtCore.QSize(280, 400))
        self.frame_22.setStyleSheet("background-color: rgb(255, 255, 235);\n"
"border-radius: 0.5em;")
        self.frame_22.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_22.setObjectName("frame_22")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.frame_22)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.frame_29 = QtWidgets.QFrame(self.frame_22)
        self.frame_29.setMaximumSize(QtCore.QSize(700, 360))
        self.frame_29.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_29.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_29.setObjectName("frame_29")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.frame_29)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.label_27 = QtWidgets.QLabel(self.frame_29)
        self.label_27.setMaximumSize(QtCore.QSize(1000, 7000))
        self.label_27.setText("")
        self.label_27.setPixmap(QtGui.QPixmap("../images/exercise/pocoh4.jpg"))
        self.label_27.setScaledContents(True)
        self.label_27.setObjectName("label_27")
        self.verticalLayout_19.addWidget(self.label_27)
        self.verticalLayout_18.addWidget(self.frame_29)
        self.frame_30 = QtWidgets.QFrame(self.frame_22)
        self.frame_30.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_30.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_30.setObjectName("frame_30")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.frame_30)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.label_28 = QtWidgets.QLabel(self.frame_30)
        self.label_28.setStyleSheet("font: 600 12pt \"Poppins\";")
        self.label_28.setWordWrap(True)
        self.label_28.setObjectName("label_28")
        self.verticalLayout_20.addWidget(self.label_28)
        self.label_29 = QtWidgets.QLabel(self.frame_30)
        self.label_29.setStyleSheet("font: 10pt \"Poppins\";")
        self.label_29.setWordWrap(True)
        self.label_29.setObjectName("label_29")
        self.verticalLayout_20.addWidget(self.label_29)
        self.url4 = QtWidgets.QPushButton(self.frame_30)
        self.url4.setStyleSheet("border-radius: 0.5em;\n"
"background-color: rgb(255, 174, 13);\n"
"padding-top: 0.30em;\n"
"padding-bottom: 0.30em;\n"
"font: 500 10pt \"Poppins\";")
        self.url4.setObjectName("url4")
        self.verticalLayout_20.addWidget(self.url4)
        self.verticalLayout_18.addWidget(self.frame_30)
        self.gridLayout_4.addWidget(self.frame_22, 1, 1, 1, 1)
        self.verticalLayout_9.addWidget(self.frame_16)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_8.addWidget(self.scrollArea)
        self.stackedWidget.addWidget(self.exercises)
        self.diet = QtWidgets.QWidget()
        self.diet.setObjectName("diet")
        self.verticalLayout_30 = QtWidgets.QVBoxLayout(self.diet)
        self.verticalLayout_30.setObjectName("verticalLayout_30")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.diet)
        self.scrollArea_2.setStyleSheet("/*  HANDLE BAR VERTICAL */\n"
"QScrollBar::handle:vertical {    \n"
"    background-color: rgb(80, 80, 122);\n"
"    min-height: 30px;\n"
"    border-radius: 7px;\n"
"}\n"
"QScrollBar::handle:vertical:hover{    \n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QScrollBar::handle:vertical:pressed {    \n"
"    background-color: rgb(67, 67, 67);\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background-color: rgb(59, 59, 90);\n"
"    height: 15px;\n"
"    border-top-left-radius: 7px;\n"
"    border-top-right-radius: 7px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:vertical:hover {    \n"
"    \n"
"    background-color: rgb(25, 25, 255);\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {    \n"
"    background-color: rgb(185, 0, 92);\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line:vertical {\n"
"    border: none;\n"
"    background-color: rgb(59, 59, 90);\n"
"    height: 15px;\n"
"    border-bottom-left-radius: 7px;\n"
"    border-bottom-right-radius: 7px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:vertical:hover {    \n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {    \n"
"    background-color: rgb(185, 0, 92);\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}")
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 728, 1752))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_31 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_31.setObjectName("verticalLayout_31")
        self.frame_37 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.frame_37.setMinimumSize(QtCore.QSize(0, 1200))
        self.frame_37.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_37.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_37.setObjectName("frame_37")
        self.verticalLayout_32 = QtWidgets.QVBoxLayout(self.frame_37)
        self.verticalLayout_32.setObjectName("verticalLayout_32")
        self.frame_54 = QtWidgets.QFrame(self.frame_37)
        self.frame_54.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_54.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_54.setObjectName("frame_54")
        self.verticalLayout_44 = QtWidgets.QVBoxLayout(self.frame_54)
        self.verticalLayout_44.setObjectName("verticalLayout_44")
        self.label_4 = QtWidgets.QLabel(self.frame_54)
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("../images/PoCoH.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_44.addWidget(self.label_4)
        self.verticalLayout_32.addWidget(self.frame_54, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.frame_55 = QtWidgets.QFrame(self.frame_37)
        self.frame_55.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_55.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_55.setObjectName("frame_55")
        self.verticalLayout_45 = QtWidgets.QVBoxLayout(self.frame_55)
        self.verticalLayout_45.setObjectName("verticalLayout_45")
        self.label_6 = QtWidgets.QLabel(self.frame_55)
        self.label_6.setStyleSheet("font: 600 18pt \"Poppins\";")
        self.label_6.setObjectName("label_6")
        self.verticalLayout_45.addWidget(self.label_6)
        self.verticalLayout_32.addWidget(self.frame_55)
        self.frame_38 = QtWidgets.QFrame(self.frame_37)
        self.frame_38.setStyleSheet("background-color: rgb(255, 255, 235);\n"
"border-radius: 0.5em;")
        self.frame_38.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_38.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_38.setObjectName("frame_38")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_38)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_41 = QtWidgets.QFrame(self.frame_38)
        self.frame_41.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_41.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_41.setObjectName("frame_41")
        self.verticalLayout_33 = QtWidgets.QVBoxLayout(self.frame_41)
        self.verticalLayout_33.setObjectName("verticalLayout_33")
        self.label_16 = QtWidgets.QLabel(self.frame_41)
        self.label_16.setMaximumSize(QtCore.QSize(400, 300))
        self.label_16.setText("")
        self.label_16.setPixmap(QtGui.QPixmap("../images/2.jpg"))
        self.label_16.setScaledContents(True)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_33.addWidget(self.label_16)
        self.horizontalLayout_3.addWidget(self.frame_41)
        self.frame_42 = QtWidgets.QFrame(self.frame_38)
        self.frame_42.setMaximumSize(QtCore.QSize(1000, 1000))
        self.frame_42.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_42.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_42.setObjectName("frame_42")
        self.verticalLayout_35 = QtWidgets.QVBoxLayout(self.frame_42)
        self.verticalLayout_35.setObjectName("verticalLayout_35")
        self.label_18 = QtWidgets.QLabel(self.frame_42)
        self.label_18.setMaximumSize(QtCore.QSize(16777215, 1000))
        self.label_18.setStyleSheet("font: 700 14pt \"Poppins\";")
        self.label_18.setObjectName("label_18")
        self.verticalLayout_35.addWidget(self.label_18)
        self.label_38 = QtWidgets.QLabel(self.frame_42)
        self.label_38.setStyleSheet("font: 300 12pt \"Poppins\";")
        self.label_38.setWordWrap(True)
        self.label_38.setObjectName("label_38")
        self.verticalLayout_35.addWidget(self.label_38)
        self.horizontalLayout_3.addWidget(self.frame_42, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.frame_43 = QtWidgets.QFrame(self.frame_38)
        self.frame_43.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_43.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_43.setObjectName("frame_43")
        self.verticalLayout_34 = QtWidgets.QVBoxLayout(self.frame_43)
        self.verticalLayout_34.setObjectName("verticalLayout_34")
        self.viewdiets1 = QtWidgets.QPushButton(self.frame_43)
        self.viewdiets1.setStyleSheet("border-radius: 0.5em;\n"
"background-color: rgb(255, 174, 13);\n"
"padding-top: 0.30em;\n"
"padding-bottom: 0.30em;\n"
"padding-left: 0.5em;\n"
"padding-right: 0.5em;\n"
"font: 500 10pt \"Poppins\";")
        self.viewdiets1.setObjectName("viewdiets1")
        self.verticalLayout_34.addWidget(self.viewdiets1, 0, QtCore.Qt.AlignBottom)
        self.horizontalLayout_3.addWidget(self.frame_43, 0, QtCore.Qt.AlignRight|QtCore.Qt.AlignBottom)
        self.verticalLayout_32.addWidget(self.frame_38)
        self.frame_39 = QtWidgets.QFrame(self.frame_37)
        self.frame_39.setStyleSheet("background-color: rgb(255, 255, 235);\n"
"border-radius: 0.5em;")
        self.frame_39.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_39.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_39.setObjectName("frame_39")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_39)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame_44 = QtWidgets.QFrame(self.frame_39)
        self.frame_44.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_44.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_44.setObjectName("frame_44")
        self.verticalLayout_37 = QtWidgets.QVBoxLayout(self.frame_44)
        self.verticalLayout_37.setObjectName("verticalLayout_37")
        self.label_39 = QtWidgets.QLabel(self.frame_44)
        self.label_39.setMaximumSize(QtCore.QSize(400, 300))
        self.label_39.setText("")
        self.label_39.setPixmap(QtGui.QPixmap("../images/disease/1.png"))
        self.label_39.setScaledContents(True)
        self.label_39.setObjectName("label_39")
        self.verticalLayout_37.addWidget(self.label_39)
        self.horizontalLayout_4.addWidget(self.frame_44)
        self.frame_45 = QtWidgets.QFrame(self.frame_39)
        self.frame_45.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_45.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_45.setObjectName("frame_45")
        self.verticalLayout_38 = QtWidgets.QVBoxLayout(self.frame_45)
        self.verticalLayout_38.setObjectName("verticalLayout_38")
        self.label_40 = QtWidgets.QLabel(self.frame_45)
        self.label_40.setStyleSheet("font: 700 14pt \"Poppins\";")
        self.label_40.setObjectName("label_40")
        self.verticalLayout_38.addWidget(self.label_40)
        self.label_41 = QtWidgets.QLabel(self.frame_45)
        self.label_41.setStyleSheet("font: 300 12pt \"Poppins\";")
        self.label_41.setWordWrap(True)
        self.label_41.setObjectName("label_41")
        self.verticalLayout_38.addWidget(self.label_41)
        self.horizontalLayout_4.addWidget(self.frame_45, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.frame_46 = QtWidgets.QFrame(self.frame_39)
        self.frame_46.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_46.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_46.setObjectName("frame_46")
        self.verticalLayout_36 = QtWidgets.QVBoxLayout(self.frame_46)
        self.verticalLayout_36.setObjectName("verticalLayout_36")
        self.viewdiets2 = QtWidgets.QPushButton(self.frame_46)
        self.viewdiets2.setStyleSheet("border-radius: 0.5em;\n"
"background-color: rgb(255, 174, 13);\n"
"padding-top: 0.30em;\n"
"padding-bottom: 0.30em;\n"
"padding-left: 0.5em;\n"
"padding-right: 0.5em;\n"
"font: 500 10pt \"Poppins\";")
        self.viewdiets2.setObjectName("viewdiets2")
        self.verticalLayout_36.addWidget(self.viewdiets2)
        self.horizontalLayout_4.addWidget(self.frame_46, 0, QtCore.Qt.AlignRight|QtCore.Qt.AlignBottom)
        self.verticalLayout_32.addWidget(self.frame_39)
        self.frame_40 = QtWidgets.QFrame(self.frame_37)
        self.frame_40.setStyleSheet("background-color: rgb(255, 255, 235);\n"
"border-radius: 0.5em;")
        self.frame_40.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_40.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_40.setObjectName("frame_40")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_40)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.frame_47 = QtWidgets.QFrame(self.frame_40)
        self.frame_47.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_47.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_47.setObjectName("frame_47")
        self.verticalLayout_41 = QtWidgets.QVBoxLayout(self.frame_47)
        self.verticalLayout_41.setObjectName("verticalLayout_41")
        self.label_42 = QtWidgets.QLabel(self.frame_47)
        self.label_42.setMaximumSize(QtCore.QSize(400, 300))
        self.label_42.setText("")
        self.label_42.setPixmap(QtGui.QPixmap("../images/disease/3.jpg"))
        self.label_42.setScaledContents(True)
        self.label_42.setObjectName("label_42")
        self.verticalLayout_41.addWidget(self.label_42)
        self.horizontalLayout_8.addWidget(self.frame_47)
        self.frame_48 = QtWidgets.QFrame(self.frame_40)
        self.frame_48.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_48.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_48.setObjectName("frame_48")
        self.verticalLayout_40 = QtWidgets.QVBoxLayout(self.frame_48)
        self.verticalLayout_40.setObjectName("verticalLayout_40")
        self.label_43 = QtWidgets.QLabel(self.frame_48)
        self.label_43.setStyleSheet("font: 700 14pt \"Poppins\";")
        self.label_43.setWordWrap(True)
        self.label_43.setObjectName("label_43")
        self.verticalLayout_40.addWidget(self.label_43)
        self.label_44 = QtWidgets.QLabel(self.frame_48)
        self.label_44.setStyleSheet("font: 300 12pt \"Poppins\";")
        self.label_44.setWordWrap(True)
        self.label_44.setObjectName("label_44")
        self.verticalLayout_40.addWidget(self.label_44)
        self.horizontalLayout_8.addWidget(self.frame_48, 0, QtCore.Qt.AlignVCenter)
        self.frame_49 = QtWidgets.QFrame(self.frame_40)
        self.frame_49.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_49.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_49.setObjectName("frame_49")
        self.verticalLayout_39 = QtWidgets.QVBoxLayout(self.frame_49)
        self.verticalLayout_39.setObjectName("verticalLayout_39")
        self.viewdiets3 = QtWidgets.QPushButton(self.frame_49)
        self.viewdiets3.setStyleSheet("border-radius: 0.5em;\n"
"background-color: rgb(255, 174, 13);\n"
"padding-top: 0.30em;\n"
"padding-bottom: 0.30em;\n"
"padding-left: 0.5em;\n"
"padding-right: 0.5em;\n"
"font: 500 10pt \"Poppins\";")
        self.viewdiets3.setObjectName("viewdiets3")
        self.verticalLayout_39.addWidget(self.viewdiets3)
        self.horizontalLayout_8.addWidget(self.frame_49, 0, QtCore.Qt.AlignRight|QtCore.Qt.AlignBottom)
        self.verticalLayout_32.addWidget(self.frame_40)
        self.verticalLayout_31.addWidget(self.frame_37)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_30.addWidget(self.scrollArea_2)
        self.stackedWidget.addWidget(self.diet)
        self.homeremedies = QtWidgets.QWidget()
        self.homeremedies.setObjectName("homeremedies")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.homeremedies)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.scrollArea_3 = QtWidgets.QScrollArea(self.homeremedies)
        self.scrollArea_3.setStyleSheet("/*  HANDLE BAR VERTICAL */\n"
"QScrollBar::handle:vertical {    \n"
"    background-color: rgb(80, 80, 122);\n"
"    min-height: 30px;\n"
"    border-radius: 7px;\n"
"}\n"
"QScrollBar::handle:vertical:hover{    \n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QScrollBar::handle:vertical:pressed {    \n"
"    background-color: rgb(67, 67, 67);\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background-color: rgb(59, 59, 90);\n"
"    height: 15px;\n"
"    border-top-left-radius: 7px;\n"
"    border-top-right-radius: 7px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:vertical:hover {    \n"
"    \n"
"    background-color: rgb(25, 25, 255);\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {    \n"
"    background-color: rgb(185, 0, 92);\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line:vertical {\n"
"    border: none;\n"
"    background-color: rgb(59, 59, 90);\n"
"    height: 15px;\n"
"    border-bottom-left-radius: 7px;\n"
"    border-bottom-right-radius: 7px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:vertical:hover {    \n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {    \n"
"    background-color: rgb(185, 0, 92);\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}")
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 1020, 1444))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.verticalLayout_42 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_3)
        self.verticalLayout_42.setObjectName("verticalLayout_42")
        self.frame_73 = QtWidgets.QFrame(self.scrollAreaWidgetContents_3)
        self.frame_73.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_73.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_73.setObjectName("frame_73")
        self.verticalLayout_63 = QtWidgets.QVBoxLayout(self.frame_73)
        self.verticalLayout_63.setObjectName("verticalLayout_63")
        self.label_59 = QtWidgets.QLabel(self.frame_73)
        self.label_59.setText("")
        self.label_59.setPixmap(QtGui.QPixmap("../images/PoCoH.png"))
        self.label_59.setObjectName("label_59")
        self.verticalLayout_63.addWidget(self.label_59)
        self.verticalLayout_42.addWidget(self.frame_73, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.frame_72 = QtWidgets.QFrame(self.scrollAreaWidgetContents_3)
        self.frame_72.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_72.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_72.setObjectName("frame_72")
        self.verticalLayout_64 = QtWidgets.QVBoxLayout(self.frame_72)
        self.verticalLayout_64.setObjectName("verticalLayout_64")
        self.label_60 = QtWidgets.QLabel(self.frame_72)
        self.label_60.setStyleSheet("font: 600 18pt \"Poppins\";")
        self.label_60.setObjectName("label_60")
        self.verticalLayout_64.addWidget(self.label_60)
        self.verticalLayout_42.addWidget(self.frame_72)
        self.frame_50 = QtWidgets.QFrame(self.scrollAreaWidgetContents_3)
        self.frame_50.setMinimumSize(QtCore.QSize(0, 1200))
        self.frame_50.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_50.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_50.setObjectName("frame_50")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.frame_50)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.frame_52 = QtWidgets.QFrame(self.frame_50)
        self.frame_52.setMaximumSize(QtCore.QSize(280, 400))
        self.frame_52.setStyleSheet("background-color: rgb(255, 255, 235);\n"
"border-radius: 0.5em;")
        self.frame_52.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_52.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_52.setObjectName("frame_52")
        self.verticalLayout_51 = QtWidgets.QVBoxLayout(self.frame_52)
        self.verticalLayout_51.setObjectName("verticalLayout_51")
        self.frame_62 = QtWidgets.QFrame(self.frame_52)
        self.frame_62.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_62.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_62.setObjectName("frame_62")
        self.verticalLayout_55 = QtWidgets.QVBoxLayout(self.frame_62)
        self.verticalLayout_55.setObjectName("verticalLayout_55")
        self.label_14 = QtWidgets.QLabel(self.frame_62)
        self.label_14.setText("")
        self.label_14.setPixmap(QtGui.QPixmap("../images/remedies/2.jpg"))
        self.label_14.setScaledContents(True)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_55.addWidget(self.label_14)
        self.verticalLayout_51.addWidget(self.frame_62)
        self.frame_63 = QtWidgets.QFrame(self.frame_52)
        self.frame_63.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_63.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_63.setObjectName("frame_63")
        self.verticalLayout_53 = QtWidgets.QVBoxLayout(self.frame_63)
        self.verticalLayout_53.setObjectName("verticalLayout_53")
        self.label_45 = QtWidgets.QLabel(self.frame_63)
        self.label_45.setStyleSheet("font: 600 12pt \"Poppins\";")
        self.label_45.setWordWrap(True)
        self.label_45.setObjectName("label_45")
        self.verticalLayout_53.addWidget(self.label_45)
        self.label_46 = QtWidgets.QLabel(self.frame_63)
        self.label_46.setStyleSheet("font: 10pt \"Poppins\";")
        self.label_46.setObjectName("label_46")
        self.verticalLayout_53.addWidget(self.label_46)
        self.remvid2 = QtWidgets.QPushButton(self.frame_63)
        self.remvid2.setStyleSheet("border-radius: 0.5em;\n"
"background-color: rgb(255, 174, 13);\n"
"padding-top: 0.30em;\n"
"padding-bottom: 0.30em;\n"
"font: 500 10pt \"Poppins\";")
        self.remvid2.setObjectName("remvid2")
        self.verticalLayout_53.addWidget(self.remvid2)
        self.verticalLayout_51.addWidget(self.frame_63)
        self.gridLayout_7.addWidget(self.frame_52, 1, 1, 1, 1)
        self.frame_53 = QtWidgets.QFrame(self.frame_50)
        self.frame_53.setMaximumSize(QtCore.QSize(280, 400))
        self.frame_53.setStyleSheet("background-color: rgb(255, 255, 235);\n"
"border-radius: 0.5em;")
        self.frame_53.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_53.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_53.setObjectName("frame_53")
        self.verticalLayout_48 = QtWidgets.QVBoxLayout(self.frame_53)
        self.verticalLayout_48.setObjectName("verticalLayout_48")
        self.frame_68 = QtWidgets.QFrame(self.frame_53)
        self.frame_68.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_68.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_68.setObjectName("frame_68")
        self.verticalLayout_65 = QtWidgets.QVBoxLayout(self.frame_68)
        self.verticalLayout_65.setObjectName("verticalLayout_65")
        self.label_53 = QtWidgets.QLabel(self.frame_68)
        self.label_53.setObjectName("label_53")
        self.verticalLayout_65.addWidget(self.label_53)
        self.verticalLayout_48.addWidget(self.frame_68)
        self.frame_69 = QtWidgets.QFrame(self.frame_53)
        self.frame_69.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_69.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_69.setObjectName("frame_69")
        self.verticalLayout_62 = QtWidgets.QVBoxLayout(self.frame_69)
        self.verticalLayout_62.setObjectName("verticalLayout_62")
        self.label_55 = QtWidgets.QLabel(self.frame_69)
        self.label_55.setStyleSheet("font: 600 12pt \"Poppins\";")
        self.label_55.setObjectName("label_55")
        self.verticalLayout_62.addWidget(self.label_55)
        self.label_54 = QtWidgets.QLabel(self.frame_69)
        self.label_54.setStyleSheet("font: 10pt \"Poppins\";")
        self.label_54.setObjectName("label_54")
        self.verticalLayout_62.addWidget(self.label_54)
        self.remvid5 = QtWidgets.QPushButton(self.frame_69)
        self.remvid5.setStyleSheet("border-radius: 0.5em;\n"
"background-color: rgb(255, 174, 13);\n"
"padding-top: 0.30em;\n"
"padding-bottom: 0.30em;\n"
"font: 500 10pt \"Poppins\";")
        self.remvid5.setObjectName("remvid5")
        self.verticalLayout_62.addWidget(self.remvid5)
        self.verticalLayout_48.addWidget(self.frame_69)
        self.gridLayout_7.addWidget(self.frame_53, 3, 0, 1, 1)
        self.frame_57 = QtWidgets.QFrame(self.frame_50)
        self.frame_57.setMaximumSize(QtCore.QSize(280, 400))
        self.frame_57.setStyleSheet("background-color: rgb(255, 255, 235);\n"
"border-radius: 0.5em;")
        self.frame_57.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_57.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_57.setObjectName("frame_57")
        self.verticalLayout_47 = QtWidgets.QVBoxLayout(self.frame_57)
        self.verticalLayout_47.setObjectName("verticalLayout_47")
        self.frame_70 = QtWidgets.QFrame(self.frame_57)
        self.frame_70.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_70.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_70.setObjectName("frame_70")
        self.verticalLayout_60 = QtWidgets.QVBoxLayout(self.frame_70)
        self.verticalLayout_60.setObjectName("verticalLayout_60")
        self.label_56 = QtWidgets.QLabel(self.frame_70)
        self.label_56.setObjectName("label_56")
        self.verticalLayout_60.addWidget(self.label_56)
        self.verticalLayout_47.addWidget(self.frame_70)
        self.frame_71 = QtWidgets.QFrame(self.frame_57)
        self.frame_71.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_71.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_71.setObjectName("frame_71")
        self.verticalLayout_61 = QtWidgets.QVBoxLayout(self.frame_71)
        self.verticalLayout_61.setObjectName("verticalLayout_61")
        self.label_57 = QtWidgets.QLabel(self.frame_71)
        self.label_57.setStyleSheet("font: 600 12pt \"Poppins\";")
        self.label_57.setObjectName("label_57")
        self.verticalLayout_61.addWidget(self.label_57)
        self.label_58 = QtWidgets.QLabel(self.frame_71)
        self.label_58.setStyleSheet("font: 10pt \"Poppins\";")
        self.label_58.setObjectName("label_58")
        self.verticalLayout_61.addWidget(self.label_58)
        self.remvid6 = QtWidgets.QPushButton(self.frame_71)
        self.remvid6.setStyleSheet("border-radius: 0.5em;\n"
"background-color: rgb(255, 174, 13);\n"
"padding-top: 0.30em;\n"
"padding-bottom: 0.30em;\n"
"font: 500 10pt \"Poppins\";")
        self.remvid6.setObjectName("remvid6")
        self.verticalLayout_61.addWidget(self.remvid6)
        self.verticalLayout_47.addWidget(self.frame_71)
        self.gridLayout_7.addWidget(self.frame_57, 3, 1, 1, 1)
        self.frame_58 = QtWidgets.QFrame(self.frame_50)
        self.frame_58.setMaximumSize(QtCore.QSize(280, 400))
        self.frame_58.setStyleSheet("background-color: rgb(255, 255, 235);\n"
"border-radius: 0.5em;")
        self.frame_58.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_58.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_58.setObjectName("frame_58")
        self.verticalLayout_50 = QtWidgets.QVBoxLayout(self.frame_58)
        self.verticalLayout_50.setObjectName("verticalLayout_50")
        self.frame_64 = QtWidgets.QFrame(self.frame_58)
        self.frame_64.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_64.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_64.setObjectName("frame_64")
        self.verticalLayout_57 = QtWidgets.QVBoxLayout(self.frame_64)
        self.verticalLayout_57.setObjectName("verticalLayout_57")
        self.label_47 = QtWidgets.QLabel(self.frame_64)
        self.label_47.setText("")
        self.label_47.setPixmap(QtGui.QPixmap("../images/remedies/3.jpg"))
        self.label_47.setScaledContents(True)
        self.label_47.setObjectName("label_47")
        self.verticalLayout_57.addWidget(self.label_47)
        self.verticalLayout_50.addWidget(self.frame_64)
        self.frame_65 = QtWidgets.QFrame(self.frame_58)
        self.frame_65.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_65.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_65.setObjectName("frame_65")
        self.verticalLayout_58 = QtWidgets.QVBoxLayout(self.frame_65)
        self.verticalLayout_58.setObjectName("verticalLayout_58")
        self.label_48 = QtWidgets.QLabel(self.frame_65)
        self.label_48.setStyleSheet("font: 600 12pt \"Poppins\";")
        self.label_48.setWordWrap(True)
        self.label_48.setObjectName("label_48")
        self.verticalLayout_58.addWidget(self.label_48)
        self.label_49 = QtWidgets.QLabel(self.frame_65)
        self.label_49.setStyleSheet("font: 10pt \"Poppins\";")
        self.label_49.setObjectName("label_49")
        self.verticalLayout_58.addWidget(self.label_49)
        self.remvid3 = QtWidgets.QPushButton(self.frame_65)
        self.remvid3.setStyleSheet("border-radius: 0.5em;\n"
"background-color: rgb(255, 174, 13);\n"
"padding-top: 0.30em;\n"
"padding-bottom: 0.30em;\n"
"font: 500 10pt \"Poppins\";")
        self.remvid3.setObjectName("remvid3")
        self.verticalLayout_58.addWidget(self.remvid3)
        self.verticalLayout_50.addWidget(self.frame_65)
        self.gridLayout_7.addWidget(self.frame_58, 2, 0, 1, 1)
        self.frame_59 = QtWidgets.QFrame(self.frame_50)
        self.frame_59.setMaximumSize(QtCore.QSize(280, 400))
        self.frame_59.setStyleSheet("background-color: rgb(255, 255, 235);\n"
"border-radius: 0.5em;")
        self.frame_59.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_59.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_59.setObjectName("frame_59")
        self.verticalLayout_49 = QtWidgets.QVBoxLayout(self.frame_59)
        self.verticalLayout_49.setObjectName("verticalLayout_49")
        self.frame_66 = QtWidgets.QFrame(self.frame_59)
        self.frame_66.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_66.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_66.setObjectName("frame_66")
        self.verticalLayout_56 = QtWidgets.QVBoxLayout(self.frame_66)
        self.verticalLayout_56.setObjectName("verticalLayout_56")
        self.label_50 = QtWidgets.QLabel(self.frame_66)
        self.label_50.setObjectName("label_50")
        self.verticalLayout_56.addWidget(self.label_50)
        self.verticalLayout_49.addWidget(self.frame_66)
        self.frame_67 = QtWidgets.QFrame(self.frame_59)
        self.frame_67.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_67.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_67.setObjectName("frame_67")
        self.verticalLayout_59 = QtWidgets.QVBoxLayout(self.frame_67)
        self.verticalLayout_59.setObjectName("verticalLayout_59")
        self.label_51 = QtWidgets.QLabel(self.frame_67)
        self.label_51.setStyleSheet("font: 600 12pt \"Poppins\";")
        self.label_51.setObjectName("label_51")
        self.verticalLayout_59.addWidget(self.label_51)
        self.label_52 = QtWidgets.QLabel(self.frame_67)
        self.label_52.setStyleSheet("font: 10pt \"Poppins\";")
        self.label_52.setObjectName("label_52")
        self.verticalLayout_59.addWidget(self.label_52)
        self.remvid4 = QtWidgets.QPushButton(self.frame_67)
        self.remvid4.setStyleSheet("border-radius: 0.5em;\n"
"background-color: rgb(255, 174, 13);\n"
"padding-top: 0.30em;\n"
"padding-bottom: 0.30em;\n"
"font: 500 10pt \"Poppins\";")
        self.remvid4.setObjectName("remvid4")
        self.verticalLayout_59.addWidget(self.remvid4)
        self.verticalLayout_49.addWidget(self.frame_67)
        self.gridLayout_7.addWidget(self.frame_59, 2, 1, 1, 1)
        self.frame_51 = QtWidgets.QFrame(self.frame_50)
        self.frame_51.setMaximumSize(QtCore.QSize(280, 400))
        self.frame_51.setStyleSheet("background-color: rgb(255, 255, 235);\n"
"border-radius: 0.5em;")
        self.frame_51.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_51.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_51.setObjectName("frame_51")
        self.verticalLayout_43 = QtWidgets.QVBoxLayout(self.frame_51)
        self.verticalLayout_43.setObjectName("verticalLayout_43")
        self.frame_60 = QtWidgets.QFrame(self.frame_51)
        self.frame_60.setMaximumSize(QtCore.QSize(700, 360))
        self.frame_60.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_60.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_60.setObjectName("frame_60")
        self.verticalLayout_54 = QtWidgets.QVBoxLayout(self.frame_60)
        self.verticalLayout_54.setObjectName("verticalLayout_54")
        self.label_7 = QtWidgets.QLabel(self.frame_60)
        self.label_7.setMaximumSize(QtCore.QSize(1000, 7000))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("../images/remedies/1.jpg"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_54.addWidget(self.label_7)
        self.verticalLayout_43.addWidget(self.frame_60)
        self.frame_61 = QtWidgets.QFrame(self.frame_51)
        self.frame_61.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_61.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_61.setObjectName("frame_61")
        self.verticalLayout_52 = QtWidgets.QVBoxLayout(self.frame_61)
        self.verticalLayout_52.setObjectName("verticalLayout_52")
        self.label_9 = QtWidgets.QLabel(self.frame_61)
        self.label_9.setStyleSheet("font: 600 12pt \"Poppins\";")
        self.label_9.setScaledContents(False)
        self.label_9.setWordWrap(True)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_52.addWidget(self.label_9)
        self.label_11 = QtWidgets.QLabel(self.frame_61)
        self.label_11.setStyleSheet("font: 10pt \"Poppins\";")
        self.label_11.setObjectName("label_11")
        self.verticalLayout_52.addWidget(self.label_11)
        self.remvid1 = QtWidgets.QPushButton(self.frame_61)
        self.remvid1.setStyleSheet("border-radius: 0.5em;\n"
"background-color: rgb(255, 174, 13);\n"
"padding-top: 0.30em;\n"
"padding-bottom: 0.30em;\n"
"font: 500 10pt \"Poppins\";")
        self.remvid1.setObjectName("remvid1")
        self.verticalLayout_52.addWidget(self.remvid1)
        self.verticalLayout_43.addWidget(self.frame_61)
        self.gridLayout_7.addWidget(self.frame_51, 1, 0, 1, 1)
        self.verticalLayout_42.addWidget(self.frame_50)
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.gridLayout_6.addWidget(self.scrollArea_3, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.homeremedies)
        self.horizontalLayout.addWidget(self.stackedWidget)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setStyleSheet("background-color: #f6f6f6;\n"
"border-radius: 1.5em;")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.bhome = QtWidgets.QPushButton(self.frame_4)
        self.bhome.setMinimumSize(QtCore.QSize(0, 50))
        self.bhome.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../images/icons/c-home.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bhome.setIcon(icon)
        self.bhome.setIconSize(QtCore.QSize(35, 35))
        self.bhome.setObjectName("bhome")
        self.horizontalLayout_5.addWidget(self.bhome)
        self.bexercise = QtWidgets.QPushButton(self.frame_4)
        self.bexercise.setMinimumSize(QtCore.QSize(0, 50))
        self.bexercise.setStyleSheet("border: none;")
        self.bexercise.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../images/icons/c-exercise.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bexercise.setIcon(icon1)
        self.bexercise.setIconSize(QtCore.QSize(35, 35))
        self.bexercise.setObjectName("bexercise")
        self.horizontalLayout_5.addWidget(self.bexercise)
        self.bdiet = QtWidgets.QPushButton(self.frame_4)
        self.bdiet.setMinimumSize(QtCore.QSize(0, 50))
        self.bdiet.setStyleSheet("border: none;")
        self.bdiet.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../images/icons/c-diet.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bdiet.setIcon(icon2)
        self.bdiet.setIconSize(QtCore.QSize(35, 35))
        self.bdiet.setObjectName("bdiet")
        self.horizontalLayout_5.addWidget(self.bdiet)
        self.bremedies = QtWidgets.QPushButton(self.frame_4)
        self.bremedies.setMinimumSize(QtCore.QSize(0, 50))
        self.bremedies.setStyleSheet("border: none;")
        self.bremedies.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../images/icons/c-home-remedies.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bremedies.setIcon(icon3)
        self.bremedies.setIconSize(QtCore.QSize(35, 35))
        self.bremedies.setObjectName("bremedies")
        self.horizontalLayout_5.addWidget(self.bremedies)
        self.bprofile = QtWidgets.QPushButton(self.frame_4)
        self.bprofile.setMinimumSize(QtCore.QSize(0, 50))
        self.bprofile.setStyleSheet("border: none;")
        self.bprofile.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../images/icons/profile-black.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bprofile.setIcon(icon4)
        self.bprofile.setIconSize(QtCore.QSize(35, 35))
        self.bprofile.setObjectName("bprofile")
        self.horizontalLayout_5.addWidget(self.bprofile)
        self.verticalLayout_2.addWidget(self.frame_4)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        l_homepage.setCentralWidget(self.centralwidget)

        self.retranslateUi(l_homepage)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(l_homepage)

    def retranslateUi(self, l_homepage):
        _translate = QtCore.QCoreApplication.translate
        l_homepage.setWindowTitle(_translate("l_homepage", "MainWindow"))
        self.blogout_2.setText(_translate("l_homepage", "Log Out"))
        self.label_17.setText(_translate("l_homepage", "FACT OF THE DAY:"))
        self.label_2.setText(_translate("l_homepage", "An apple a day keeps the doctor away!"))
        self.label_13.setText(_translate("l_homepage", "PRECAUTIONS"))
        self.name.setText(_translate("l_homepage", "John Doe"))
        self.beditprof.setText(_translate("l_homepage", "Edit Profile"))
        self.blogout.setText(_translate("l_homepage", "Log Out"))
        self.label_5.setText(_translate("l_homepage", "Username"))
        self.username.setText(_translate("l_homepage", "<username of person>"))
        self.label_8.setText(_translate("l_homepage", "Email"))
        self.email.setText(_translate("l_homepage", "<Email of person>"))
        self.label_10.setText(_translate("l_homepage", "Mobile Number"))
        self.mobile.setText(_translate("l_homepage", "<Mobile of person>"))
        self.label_12.setText(_translate("l_homepage", "Date of Birth"))
        self.dob.setText(_translate("l_homepage", "<dob of person>"))
        self.label_37.setText(_translate("l_homepage", "Exercises for better health "))
        self.label_32.setText(_translate("l_homepage", "Post Acute Covid 19 Advice and Rehabilitation"))
        self.label_31.setText(_translate("l_homepage", "This video explains what Post Acute COVID-19 (Long Covid) is and how to help patients or yourself with recovery."))
        self.url5.setText(_translate("l_homepage", "Click here to view the video"))
        self.label_34.setText(_translate("l_homepage", "Post Acute Covid 19 Advice and Rehabilitation"))
        self.label_35.setText(_translate("l_homepage", "This video explains what Post Acute COVID-19 (Long Covid) is and how to help patients or yourself with recovery."))
        self.url6.setText(_translate("l_homepage", "Click here to view the video"))
        self.label_19.setText(_translate("l_homepage", "Post Acute Covid 19 Advice and Rehabilitation"))
        self.label_20.setText(_translate("l_homepage", "This video explains what Post Acute COVID-19 (Long Covid) is and how to help patients or yourself with recovery."))
        self.url1.setText(_translate("l_homepage", "Click here to view the video"))
        self.label_22.setText(_translate("l_homepage", "Post Acute Covid 19 Advice and Rehabilitation"))
        self.label_23.setText(_translate("l_homepage", "This video explains what Post Acute COVID-19 (Long Covid) is and how to help patients or yourself with recovery."))
        self.url2.setText(_translate("l_homepage", "Click here to view the video"))
        self.label_25.setText(_translate("l_homepage", "Post Acute Covid 19 Advice and Rehabilitation"))
        self.label_26.setText(_translate("l_homepage", "This video explains what Post Acute COVID-19 (Long Covid) is and how to help patients or yourself with recovery."))
        self.url3.setText(_translate("l_homepage", "Click here to view the video"))
        self.label_28.setText(_translate("l_homepage", "Post Acute Covid 19 Advice and Rehabilitation"))
        self.label_29.setText(_translate("l_homepage", "This video explains what Post Acute COVID-19 (Long Covid) is and how to help patients or yourself with recovery."))
        self.url4.setText(_translate("l_homepage", "Click here to view the video"))
        self.label_6.setText(_translate("l_homepage", "Recommended Diets for some diseases"))
        self.label_18.setText(_translate("l_homepage", "Covid - 19"))
        self.label_38.setText(_translate("l_homepage", "Prefer foods that contain healthy sources of unsaturated fats, such as fish and nuts. To limit saturated fats, trim excess fat from meat and poultry and choose skinless options. Reduce foods such as red and fatty meats, butter and full-fat dairy products, palm oil, coconut oil, solid shortening and lard"))
        self.viewdiets1.setText(_translate("l_homepage", "View Diets"))
        self.label_40.setText(_translate("l_homepage", "Chicken Pox"))
        self.label_41.setText(_translate("l_homepage", "There is a world-wide trend that shows the disease to occur during this transition phase. Person suffering from chicken pox needs to be well hydrated."))
        self.viewdiets2.setText(_translate("l_homepage", "View Diets"))
        self.label_43.setText(_translate("l_homepage", "Dengue"))
        self.label_44.setText(_translate("l_homepage", "Food that is rich in protein and iron (e.g. meat, eggs and liver) are recommended to help you recover from dengue fever. These help prevent anemia and strengthen the immune system."))
        self.viewdiets3.setText(_translate("l_homepage", "View Diets"))
        self.label_60.setText(_translate("l_homepage", "Home Remedies for various diseases"))
        self.label_45.setText(_translate("l_homepage", "Home care tips for Sidubu | Home Care Chickenpox"))
        self.label_46.setText(_translate("l_homepage", "TextLabel"))
        self.remvid2.setText(_translate("l_homepage", "Click here to view the video"))
        self.label_53.setText(_translate("l_homepage", "TextLabel"))
        self.label_55.setText(_translate("l_homepage", "TextLabel"))
        self.label_54.setText(_translate("l_homepage", "TextLabel"))
        self.remvid5.setText(_translate("l_homepage", "Click here to view the video"))
        self.label_56.setText(_translate("l_homepage", "TextLabel"))
        self.label_57.setText(_translate("l_homepage", "TextLabel"))
        self.label_58.setText(_translate("l_homepage", "TextLabel"))
        self.remvid6.setText(_translate("l_homepage", "Click here to view the video"))
        self.label_48.setText(_translate("l_homepage", "Coronavirus Pandemic: 4 Ayurvedic Drinks To Boost Immunity | NewsMo"))
        self.label_49.setText(_translate("l_homepage", "TextLabel"))
        self.remvid3.setText(_translate("l_homepage", "Click here to view the video"))
        self.label_50.setText(_translate("l_homepage", "TextLabel"))
        self.label_51.setText(_translate("l_homepage", "TextLabel"))
        self.label_52.setText(_translate("l_homepage", "TextLabel"))
        self.remvid4.setText(_translate("l_homepage", "Click here to view the video"))
        self.label_9.setText(_translate("l_homepage", "Without Medicines Natural Home Remedy for Dengue and Malaria"))
        self.label_11.setText(_translate("l_homepage", "TextLabel"))
        self.remvid1.setText(_translate("l_homepage", "Click here to view the video"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    l_homepage = QtWidgets.QMainWindow()
    ui = Ui_l_homepage()
    ui.setupUi(l_homepage)
    l_homepage.show()
    sys.exit(app.exec_())
