# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Login.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Login(object):
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.resize(954, 640)
        self.label = QtWidgets.QLabel(Login)
        self.label.setGeometry(QtCore.QRect(-2, 5, 951, 621))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../images/login-bg.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.lineEdit_2 = QtWidgets.QLineEdit(Login)
        self.lineEdit_2.setGeometry(QtCore.QRect(510, 360, 381, 41))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"font: 12pt \"Poppins\";\n"
"border-bottom:2px solid #2a2a2a;\n"
"border-radius: 30px;\n"
"color:#2a2a2a;\n"
"padding-bottom:7px;\n"
"padding-left:5px;")
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_3 = QtWidgets.QLabel(Login)
        self.label_3.setGeometry(QtCore.QRect(510, 220, 121, 65))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: white;")
        self.label_3.setObjectName("label_3")
        self.bregister = QtWidgets.QPushButton(Login)
        self.bregister.setGeometry(QtCore.QRect(510, 440, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        self.bregister.setFont(font)
        self.bregister.setStyleSheet("QPushButton#bregister{\n"
"    font: 14pt \"Poppins\";\n"
" color: #ffffff;\n"
" font-size: 18px;\n"
" border-radius: 0.5em;\n"
" border: 1px solid #e8e8e8;\n"
"}\n"
"\n"
"QPushButton#bregister:hover {\n"
"font: 14pt \"Poppins\";\n"
" border: 2px solid white;\n"
"color:#090909;\n"
" background: #e8e8e8;\n"
"}\n"
"")
        self.bregister.setObjectName("bregister")
        self.lineEdit = QtWidgets.QLineEdit(Login)
        self.lineEdit.setGeometry(QtCore.QRect(510, 300, 381, 41))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"font: 12pt \"Poppins\";\n"
"border-bottom:2px solid #2a2a2a;\n"
"border-radius: 30px;\n"
"color:#2a2a2a;\n"
"padding-bottom:7px;\n"
"padding-left: 5px;")
        self.lineEdit.setObjectName("lineEdit")
        self.blogin = QtWidgets.QPushButton(Login)
        self.blogin.setGeometry(QtCore.QRect(730, 440, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        self.blogin.setFont(font)
        self.blogin.setStyleSheet("QPushButton#blogin{\n"
"font: 14pt \"Poppins\";\n"
" color: #090909;\n"
" font-size: 18px;\n"
" border-radius: 0.5em;\n"
" background: #e8e8e8;\n"
" border: 1px solid #e8e8e8;\n"
"}\n"
"\n"
"\n"
"QPushButton#blogin:hover {\n"
"font: 14pt \"Poppins\";\n"
" border: 1px solid white;\n"
"}")
        self.blogin.setObjectName("blogin")
        self.label_2 = QtWidgets.QLabel(Login)
        self.label_2.setGeometry(QtCore.QRect(510, 60, 251, 101))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("../images/PoCoH.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Login)
        QtCore.QMetaObject.connectSlotsByName(Login)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "Dialog"))
        self.lineEdit_2.setPlaceholderText(_translate("Login", "Enter Password"))
        self.label_3.setText(_translate("Login", "Login"))
        self.bregister.setText(_translate("Login", "Register"))
        self.lineEdit.setPlaceholderText(_translate("Login", "Enter Username"))
        self.blogin.setText(_translate("Login", "Login"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Login = QtWidgets.QDialog()
    ui = Ui_Login()
    ui.setupUi(Login)
    Login.show()
    sys.exit(app.exec_())
