# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'resgister-section2.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Register2(object):
    def setupUi(self, Register2):
        Register2.setObjectName("Register2")
        Register2.resize(915, 641)
        self.centralwidget = QtWidgets.QWidget(Register2)
        self.centralwidget.setObjectName("centralwidget")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 260, 221, 91))
        self.label_3.setStyleSheet("background-color: rgb(149, 167, 255);")
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("images/PoCoH.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 921, 601))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("images/login-bg.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(500, 50, 371, 31))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setKerning(True)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_9.setObjectName("label_9")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(500, 100, 391, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setKerning(True)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_13.setObjectName("label_13")
        self.tusername = QtWidgets.QLineEdit(self.centralwidget)
        self.tusername.setGeometry(QtCore.QRect(500, 210, 301, 41))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        self.tusername.setFont(font)
        self.tusername.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"font: 12pt \"Poppins\";\n"
"border-bottom:2px solid #2a2a2a;\n"
"border-radius: 30px;\n"
"color:#2a2a2a;\n"
"padding-bottom:7px;")
        self.tusername.setObjectName("tusername")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(500, 170, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.bback = QtWidgets.QPushButton(self.centralwidget)
        self.bback.setGeometry(QtCore.QRect(500, 490, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        self.bback.setFont(font)
        self.bback.setStyleSheet("QPushButton#bback{\n"
"    font: 14pt \"Poppins\";\n"
" color: #ffffff;\n"
" font-size: 18px;\n"
" border-radius: 0.5em;\n"
" border: 1px solid #e8e8e8;\n"
"}\n"
"\n"
"QPushButton#bback:hover {\n"
" border: 1px solid white;\n"
"color:#090909;\n"
" background: #e8e8e8;\n"
"}\n"
"")
        self.bback.setObjectName("bback")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(500, 380, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.tpass = QtWidgets.QLineEdit(self.centralwidget)
        self.tpass.setGeometry(QtCore.QRect(500, 310, 301, 41))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        self.tpass.setFont(font)
        self.tpass.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"font: 12pt \"Poppins\";\n"
"border-bottom:2px solid #2a2a2a;\n"
"border-radius: 30px;\n"
"color:#2a2a2a;\n"
"padding-bottom:7px;")
        self.tpass.setEchoMode(QtWidgets.QLineEdit.Password)
        self.tpass.setObjectName("tpass")
        self.bsubmit = QtWidgets.QPushButton(self.centralwidget)
        self.bsubmit.setGeometry(QtCore.QRect(680, 490, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        self.bsubmit.setFont(font)
        self.bsubmit.setStyleSheet("QPushButton#bsubmit{\n"
"font: 14pt \"Poppins\";\n"
" color: #090909;\n"
" font-size: 18px;\n"
" border-radius: 0.5em;\n"
" background: #e8e8e8;\n"
" border: 1px solid #e8e8e8;\n"
"}\n"
"\n"
"QPushButton#bsubmit:hover {\n"
" border: 1px solid white;\n"
"}\n"
"")
        self.bsubmit.setObjectName("bsubmit")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(500, 270, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.trepass = QtWidgets.QLineEdit(self.centralwidget)
        self.trepass.setGeometry(QtCore.QRect(500, 420, 301, 41))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        self.trepass.setFont(font)
        self.trepass.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border-bottom:2px solid #2a2a2a;\n"
"font: 12pt \"Poppins\";\n"
"border-radius: 30px;\n"
"color:#2a2a2a;\n"
"padding-bottom:7px;")
        self.trepass.setEchoMode(QtWidgets.QLineEdit.Password)
        self.trepass.setObjectName("trepass")
        self.label.raise_()
        self.label_3.raise_()
        self.label_9.raise_()
        self.label_13.raise_()
        self.tusername.raise_()
        self.label_5.raise_()
        self.bback.raise_()
        self.label_8.raise_()
        self.tpass.raise_()
        self.bsubmit.raise_()
        self.label_7.raise_()
        self.trepass.raise_()
        Register2.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Register2)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 915, 22))
        self.menubar.setObjectName("menubar")
        Register2.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Register2)
        self.statusbar.setObjectName("statusbar")
        Register2.setStatusBar(self.statusbar)

        self.retranslateUi(Register2)
        QtCore.QMetaObject.connectSlotsByName(Register2)

    def retranslateUi(self, Register2):
        _translate = QtCore.QCoreApplication.translate
        Register2.setWindowTitle(_translate("Register2", "MainWindow"))
        self.label_9.setText(_translate("Register2", "REGISTER"))
        self.label_13.setText(_translate("Register2", "Section 2: Login Credentials"))
        self.tusername.setPlaceholderText(_translate("Register2", "  Create username"))
        self.label_5.setText(_translate("Register2", "Username"))
        self.bback.setText(_translate("Register2", "Back"))
        self.label_8.setText(_translate("Register2", "Re-Enter Password"))
        self.tpass.setPlaceholderText(_translate("Register2", "  Create password"))
        self.bsubmit.setText(_translate("Register2", "Submit"))
        self.label_7.setText(_translate("Register2", "Password"))
        self.trepass.setPlaceholderText(_translate("Register2", "  Re-Enter password"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Register2 = QtWidgets.QMainWindow()
    ui = Ui_Register2()
    ui.setupUi(Register2)
    Register2.show()
    sys.exit(app.exec_())
