# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'resgister-section1.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Register1(object):
    def setupUi(self, Register1):
        Register1.setObjectName("Register1")
        Register1.resize(915, 641)
        self.centralwidget = QtWidgets.QWidget(Register1)
        self.centralwidget.setObjectName("centralwidget")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(500, 400, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 260, 221, 91))
        self.label_3.setStyleSheet("background-color: rgb(149, 167, 255);")
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("images/PoCoH.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 921, 601))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("images/login-bg.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_6.setGeometry(QtCore.QRect(500, 340, 281, 41))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        self.lineEdit_6.setFont(font)
        self.lineEdit_6.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"font: 12pt \"Poppins\";\n"
"border-bottom:2px solid #2a2a2a;\n"
"border-radius: 30px;\n"
"color:#2a2a2a;\n"
"padding-bottom:7px;\n"
"padding-left:5px;")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.bnext = QtWidgets.QPushButton(self.centralwidget)
        self.bnext.setGeometry(QtCore.QRect(500, 520, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        self.bnext.setFont(font)
        self.bnext.setStyleSheet("QPushButton#bnext{\n"
"    font: 18px \"Poppins\";\n"
" color: #090909;\n"
"\n"
" border-radius: 0.5em;\n"
" background: #e8e8e8;\n"
" border: 1px solid #e8e8e8;\n"
"}\n"
"\n"
"QPushButton#bnext:hover {\n"
"font: 18px \"Poppins\"; \n"
"border: 1px solid white;\n"
"}\n"
"")
        self.bnext.setObjectName("bnext")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(500, 220, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("font: 14pt \"Poppins\";")
        self.label_11.setObjectName("label_11")
        self.dateEdit = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEdit.setGeometry(QtCore.QRect(500, 440, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        self.dateEdit.setFont(font)
        self.dateEdit.setStyleSheet("font: 12pt \"Poppins\";")
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setObjectName("dateEdit")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(500, 30, 351, 31))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setKerning(True)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_9.setObjectName("label_9")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(500, 130, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("font: 14pt \"Poppins\";")
        self.label_6.setObjectName("label_6")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(500, 310, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("font: 14pt \"Poppins\";")
        self.label_12.setObjectName("label_12")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_5.setGeometry(QtCore.QRect(500, 250, 281, 41))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        self.lineEdit_5.setFont(font)
        self.lineEdit_5.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border-bottom:2px solid #2a2a2a;\n"
"font: 12pt \"Poppins\";\n"
"border-radius: 30px;\n"
"color:#2a2a2a;\n"
"padding-bottom:7px;\n"
"padding-left:5px;")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(500, 160, 281, 41))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"font: 12pt \"Poppins\";\n"
"border-bottom:2px solid #2a2a2a;\n"
"border-radius: 30px;\n"
"color:#2a2a2a;\n"
"padding-bottom:7px;\n"
"padding-left:5px;")
        self.lineEdit.setObjectName("lineEdit")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(500, 80, 401, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setKerning(True)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_13.setObjectName("label_13")
        self.label.raise_()
        self.label_10.raise_()
        self.label_3.raise_()
        self.lineEdit_6.raise_()
        self.bnext.raise_()
        self.label_11.raise_()
        self.dateEdit.raise_()
        self.label_9.raise_()
        self.label_6.raise_()
        self.label_12.raise_()
        self.lineEdit_5.raise_()
        self.lineEdit.raise_()
        self.label_13.raise_()
        Register1.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Register1)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 915, 22))
        self.menubar.setObjectName("menubar")
        Register1.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Register1)
        self.statusbar.setObjectName("statusbar")
        Register1.setStatusBar(self.statusbar)

        self.retranslateUi(Register1)
        QtCore.QMetaObject.connectSlotsByName(Register1)

    def retranslateUi(self, Register1):
        _translate = QtCore.QCoreApplication.translate
        Register1.setWindowTitle(_translate("Register1", "MainWindow"))
        self.label_10.setText(_translate("Register1", "Date of Birth"))
        self.lineEdit_6.setPlaceholderText(_translate("Register1", "Enter your name"))
        self.bnext.setText(_translate("Register1", "Next"))
        self.label_11.setText(_translate("Register1", "Email"))
        self.label_9.setText(_translate("Register1", "REGISTER"))
        self.label_6.setText(_translate("Register1", "Name"))
        self.label_12.setText(_translate("Register1", "Phone Number"))
        self.lineEdit_5.setPlaceholderText(_translate("Register1", "Enter your name"))
        self.lineEdit.setPlaceholderText(_translate("Register1", "Enter your name"))
        self.label_13.setText(_translate("Register1", "Section 1: Personal Information"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Register1 = QtWidgets.QMainWindow()
    ui = Ui_Register1()
    ui.setupUi(Register1)
    Register1.show()
    sys.exit(app.exec_())
